import {readFileSync,existsSync} from 'node:fs';
import {runInNewContext} from 'node:vm';
import assert from 'node:assert/strict';
const html=readFileSync('web/account.html','utf8');
const code=readFileSync('src/account-page.js','utf8').replace(/^import .*;\n/gm,'');
class Node{constructor(){this.children=[];this.hidden=false;this.disabled=false;this.value='';this.textContent='';}append(...items){this.children.push(...items);if(!this.value&&items[0]?.value)this.value=items[0].value;}replaceChildren(...items){this.children=items;this.value='';}focus(){}setAttribute(){}addEventListener(){}}
async function page(mode){const ids=[...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]);const nodes=Object.fromEntries(ids.map(id=>[id,new Node()]));const member={id:'member',email:'member@example.test'};const profile={id:'member',display_name:'Juan',blocked:mode==='blocked',email:member.email};const state=mode==='guest'?null:{user:member,profile,isAdmin:mode==='admin',profiles:[profile,{id:'other',email:'other@example.test',blocked:false}],tools:[{id:'upscale',name:'Mejorar imágenes'}]};const calls=[];
const context={document:{getElementById:id=>nodes[id],createElement:()=>new Node()},client:{auth:{getSession:async()=>({data:{session:state?{access_token:'valid'}:null}}),signOut:async()=>({error:null}),onAuthStateChange:()=>{}}},configured:true,identity:async()=>state,rpc:async(name,args)=>calls.push([name,args]),routes:{upscale:'upscale.html'},allowed:s=>Boolean(s&&!s.profile.blocked),safeReturn:()=> 'index.html',syncServerSession:async()=>{},setToolEnabled:async()=>{},mountAuth:()=>({setMode(){}}),authError:e=>e.message,location:{search:'',replace(){}},history:{replaceState(){}},sessionStorage:{getItem(){},setItem(){},removeItem(){}},URLSearchParams,setTimeout};await runInNewContext('(async()=>{'+code+'})()',context);return {nodes,calls};}
assert.match(html,/id="loginPanel"[^>]*hidden/,'login stays hidden until the session check finishes');
const guest=await page('guest');assert.equal(guest.nodes.adminPanel.hidden,true);assert.equal(guest.nodes.loginPanel.hidden,false);
const member=await page('member');assert.equal(member.nodes.memberPanel.hidden,false);assert.equal(member.nodes.adminPanel.hidden,true);assert.equal(member.nodes.myTools.children[0].children.length,3);assert.equal(member.nodes.myTools.children[0].children[1].textContent,'Gratis · Sin vencimiento');
const blocked=await page('blocked');assert.match(blocked.nodes.memberRole.textContent,/suspendida/);assert.equal(blocked.nodes.myTools.children[0].children.length,2);
const admin=await page('admin');assert.equal(admin.nodes.adminPanel.hidden,false);assert.equal(admin.nodes.userCount.textContent,'2');assert.equal(admin.nodes.blockUser.disabled,true);admin.nodes.users.value='other';admin.nodes.users.onchange();await admin.nodes.blockUser.onclick();const blockCall=admin.calls.find(c=>c[0]==='lz_set_blocked');assert.equal(blockCall[1].target,'other');assert.equal(blockCall[1].value,true);
for(const m of html.matchAll(/(?:src|href)="([^"?#]+)"/g))if(!m[1].includes('://'))assert.ok(existsSync('web/'+m[1]),m[1]);
const authCode=readFileSync('src/auth-ui.js','utf8').replace(/^import .*;\n/gm,'').replace(/export /g,'');
async function form(mode,{email='user@example.test',password='password123',confirm='password123',error=null,session=null}={}){const selectors=new Map();const make=s=>{if(!selectors.has(s)){const n=new Node();n.setAttribute=()=>{};n.focus=()=>{};n.dataset={mode:s.includes('register')?'register':'login'};selectors.set(s,n);}return selectors.get(s);};const fields={email:{value:email},password:{value:password},confirm:{value:confirm},full_name:{value:'Juan'},remember:{checked:true}};make('.auth-form').elements=fields;make('.auth-form').reset=()=>{};const tabs=[make('[data-mode="login"]'),make('[data-mode="register"]')];const container={innerHTML:'',querySelector:make,querySelectorAll:s=>s==='[data-mode]'?tabs:[...tabs,make('.auth-submit')]};const calls=[];let successes=0;const record=name=>async args=>{calls.push([name,args]);return {error,data:{session}};};const context={container,client:{auth:{signInWithPassword:record('password'),signUp:record('signup'),resetPasswordForEmail:record('reset'),updateUser:record('update'),getSession:async()=>({data:{session}})}},configured:true,rememberSession:()=>true,setRememberSession:()=>{},syncServerSession:async()=>calls.push(['sync']),location:{href:'https://test.example/index.html'},URL};runInNewContext(authCode+`;mountAuth(container,{mode:${JSON.stringify(mode)},onSuccess:()=>{successes++}});`,{...context,get successes(){return successes;},set successes(v){successes=v;}});await make('.auth-form').onsubmit({preventDefault(){}});return {calls,message:make('.auth-message').textContent};}
let f=await form('login');assert.equal(f.calls[0][0],'password');assert.equal(f.calls[0][1].email,'user@example.test');assert.ok(f.calls.some(c=>c[0]==='sync'));
f=await form('register');assert.equal(f.calls[0][0],'signup');assert.equal(f.calls[0][1].options.data.full_name,'Juan');assert.match(f.message,/confirmar tu correo/);
f=await form('register',{confirm:'different'});assert.equal(f.calls.length,0);assert.match(f.message,/no coinciden/);
f=await form('reset');assert.equal(f.calls[0][0],'reset');assert.equal(f.calls[0][1],'user@example.test');assert.match(f.message,/Si ese correo tiene una cuenta/);
f=await form('login',{error:{message:'Invalid login credentials'}});assert.match(f.message,/incorrectos/);assert.ok(!f.calls.some(c=>c[0]==='sync'));
console.log('PASS: password sign-in, free registration, confirmation notice, mismatch, recovery, invalid credentials, free member/admin/blocked states and targeted suspension.');

// Remembered sessions persist across new tabs; unchecked sessions use only this tab.
class Storage {constructor(){this.data=new Map();}get length(){return this.data.size;}key(i){return [...this.data.keys()][i];}getItem(k){return this.data.get(k)??null;}setItem(k,v){this.data.set(k,String(v));}removeItem(k){this.data.delete(k);}}
const durable=new Storage(),temporary=new Storage();
const clientCode=readFileSync('src/account-client.js','utf8').replace(/^import .*;\n/gm,'').replace(/export /g,'');
const storageContext={localStorage:durable,sessionStorage:temporary,AUTH_CONFIG:{},createClient(){}};
runInNewContext(clientCode+';globalThis.api={sessionStorageAdapter,setRememberSession,rememberSession};',storageContext);
const api=storageContext.api;api.sessionStorageAdapter.setItem('sb-test-auth-token','session-data');assert.equal(durable.getItem('sb-test-auth-token'),'session-data');api.setRememberSession(false);assert.equal(durable.getItem('sb-test-auth-token'),null);assert.equal(temporary.getItem('sb-test-auth-token'),'session-data');api.sessionStorageAdapter.setItem('sb-test-auth-token','refreshed');assert.equal(temporary.getItem('sb-test-auth-token'),'refreshed');api.setRememberSession(true);assert.equal(durable.getItem('sb-test-auth-token'),'refreshed');api.sessionStorageAdapter.removeItem('sb-test-auth-token');assert.equal(durable.getItem('sb-test-auth-token'),null);assert.equal(temporary.getItem('sb-test-auth-token'),null);
