import assert from 'node:assert/strict';
import {readFileSync,statSync} from 'node:fs';
import {processPixels,removeIsolatedResidue,spot} from './web/processor.js';
import {pngDensity,crc32} from './web/png.js';
import {assemblePng} from './web/exporter.js';
const base={removeOn:false,removeColor:'#000000',removeTolerance:0,softness:0,recolorOn:false,fromColor:'#ffffff',toColor:'#ff0000',recolorTolerance:0,keepShading:false,halftoneOn:false,halftoneMode:'color',halftoneColor:'#000000',halftoneRange:100,shape:'circle',lpi:25,angle:0,coverage:50,dualHalftone:false,lpi2:23,angle2:75};
const a=new Uint8ClampedArray([0,0,0,255,255,255,255,255,255,0,0,80]);processPixels(a,3,1,{...base,removeOn:true},100);assert.deepEqual([...a],[0,0,0,0,255,255,255,255,255,0,0,80]);
const b=new Uint8ClampedArray([255,255,255,128,20,20,20,255]);processPixels(b,2,1,{...base,recolorOn:true},100);assert.deepEqual([...b],[255,0,0,128,20,20,20,255]);
const residue=new Uint8ClampedArray(12*8*4);for(let y=2;y<6;y++)for(let x=3;x<8;x++)residue.set([10,10,10,255],(y*12+x)*4);residue.set([10,10,10,255],(1*12+10)*4);residue.set([10,10,10,255],(6*12+1)*4);residue.set([10,10,10,255],(4*12)*4);removeIsolatedResidue(residue,12,8,118,.3);assert.equal(residue[(1*12+10)*4+3],0);assert.equal(residue[(6*12+1)*4+3],0);assert.equal(residue[(4*12)*4+3],255);assert.equal(residue[(3*12+5)*4+3],255);
for(const shape of ['circle','square','diamond','line']){const data=new Uint8ClampedArray(200*200*4).fill(255);processPixels(data,200,200,{...base,halftoneOn:true,shape,lpi:25.4},1000);let solid=0;for(let i=3;i<data.length;i+=4){assert.ok(data[i]===0||data[i]===255);if(data[i]===255)solid++;}assert.ok(Math.abs(solid/40000-.5)<.06,shape+' area coverage');assert.equal(spot(0,0,shape),0);const full=new Uint8ClampedArray(400).fill(255);processPixels(full,10,10,{...base,halftoneOn:true,shape,coverage:100},100);assert.ok(full.every(x=>x===255));}
const gradient=new Uint8ClampedArray(300*20*4);for(let y=0;y<20;y++)for(let x=0;x<300;x++){const i=(y*300+x)*4,v=Math.round(x/299*255);gradient.set([v,v,v,255],i);}processPixels(gradient,300,20,{...base,halftoneOn:true,coverage:100},300);let black=0,mid=0,white=0;for(let y=0;y<20;y++){black+=gradient[(y*300+0)*4+3];white+=gradient[(y*300+299)*4+3];for(let x=130;x<170;x++)mid+=gradient[(y*300+x)*4+3];}assert.equal(black,0);assert.ok(mid>0&&mid<20*40*255);assert.equal(white,20*255);
const whole=new Uint8ClampedArray(80*80*4).fill(255),top=whole.slice(0,80*40*4),bottom=whole.slice(80*40*4);processPixels(whole,80,80,{...base,halftoneOn:true,shape:'diamond'},200);processPixels(top,80,40,{...base,halftoneOn:true,shape:'diamond'},200,0,0);processPixels(bottom,80,40,{...base,halftoneOn:true,shape:'diamond'},200,0,40);assert.deepEqual([...top,...bottom],[...whole]);
const dual=new Uint8ClampedArray(400*400*4).fill(255);processPixels(dual,400,400,{...base,halftoneOn:true,dualHalftone:true,lpi:25.4,lpi2:23,angle:15,angle2:75},1000);let dualSolid=0;for(let i=3;i<dual.length;i+=4){assert.ok(dual[i]===0||dual[i]===255);if(dual[i]===255)dualSolid++;}assert.ok(Math.abs(dualSolid/(400*400)-.5)<.06,'dual screen preserves requested density');const dualWhole=new Uint8ClampedArray(80*80*4).fill(255),dualTop=dualWhole.slice(0,80*40*4),dualBottom=dualWhole.slice(80*40*4);const dualParams={...base,halftoneOn:true,dualHalftone:true,shape:'diamond',angle:35,angle2:95};processPixels(dualWhole,80,80,dualParams,200);processPixels(dualTop,80,40,dualParams,200,0,0);processPixels(dualBottom,80,40,dualParams,200,0,40);assert.deepEqual([...dualTop,...dualBottom],[...dualWhole]);
// Physical frequency agrees when output pixel density changes.
for(const scale of [100,200]){const d=new Uint8ClampedArray(scale*scale*4).fill(255);processPixels(d,scale,scale,{...base,halftoneOn:true,shape:'square'},scale);let transitions=0;for(let x=1;x<scale;x++)if(d[(Math.floor(scale*.05)*scale+x)*4+3]!==d[(Math.floor(scale*.05)*scale+x-1)*4+3])transitions++;assert.ok(transitions>=18&&transitions<=21,'physical LPI remains stable');}
const png=Uint8Array.from(Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j5N0AAAAASUVORK5CYII=','base64'));
let out=pngDensity(png,300),count=0;for(let o=8;o<out.length;){const len=new DataView(out.buffer).getUint32(o),type=String.fromCharCode(...out.slice(o+4,o+8));if(type==='pHYs'){count++;assert.equal(new DataView(out.buffer).getUint32(o+8),11811);assert.equal(new DataView(out.buffer).getUint32(o+12),11811);assert.equal(out[o+16],1);assert.equal(new DataView(out.buffer).getUint32(o+17),crc32(out.slice(o+4,o+17)));}o+=len+12;}assert.equal(count,1);out=pngDensity(out,150);assert.equal([...out].filter((_,i)=>String.fromCharCode(...out.slice(i,i+4))==='pHYs').length,1);
assert.throws(()=>pngDensity(new Uint8Array(10),300));
const raw=Uint8Array.from([0,12,34,56,78]),compressor=new CompressionStream('deflate'),compressedPromise=new Response(compressor.readable).arrayBuffer(),writer=compressor.writable.getWriter();await writer.write(raw);await writer.close();const assembled=new Uint8Array(await assemblePng(1,1,300,new Uint8Array(await compressedPromise)).arrayBuffer());assert.deepEqual([...assembled.slice(0,8)],[137,80,78,71,13,10,26,10]);const idat=[];for(let o=8;o<assembled.length;){const len=new DataView(assembled.buffer,assembled.byteOffset+o,4).getUint32(0),type=String.fromCharCode(...assembled.slice(o+4,o+8));if(type==='IDAT')idat.push(assembled.slice(o+8,o+8+len));o+=len+12;}const packed=new Blob(idat).stream().pipeThrough(new DecompressionStream('deflate')),decoded=new Uint8Array(await new Response(packed).arrayBuffer());assert.deepEqual([...decoded],[...raw]);
const cnnModel='./web/models/realesr-general-x4v3-cnn/model.onnx';assert.ok(statSync(cnnModel).size>4_000_000&&statSync(cnnModel).size<6_000_000);assert.ok(statSync('./web/vendor/onnxruntime/ort.webgpu.bundle.min.mjs').size>300_000);assert.ok(statSync('./web/vendor/onnxruntime/ort-wasm-simd-threaded.jsep.wasm').size>20_000_000);assert.ok(statSync('./web/idb-cache.js').size>1_000);const html=readFileSync('./web/editor.html','utf8');assert.match(html,/Mejorar imagen ×2/);assert.match(html,/MEJORAR IMAGEN/);assert.match(html,/Aumenta la resolución/);assert.equal((html.match(/id="aiUpscale"/g)||[]).length,1);assert.ok(!html.includes('fastUpscale'));const app=readFileSync('./web/app.js','utf8'),engine=readFileSync('./web/ai-engine.js','utf8');assert.match(app,/createOnnxSuperResolution/);assert.match(app,/CNN_TILE_SIZE/);assert.match(app,/onTile\?\./);assert.match(app,/bloque \$\{done\}\/\$\{total\}/);assert.match(engine,/InferenceSession\.create/);assert.match(engine,/realesr-general-x4v3-cnn/);assert.match(engine,/CNN_TILE_SIZE=160/);assert.match(engine,/optimizing/);assert.match(engine,/createIndexedDbCache/);assert.ok(!app.includes('transformers.min.js'));assert.ok(!app.includes('cdn.jsdelivr.net'));
const mockupHtml=readFileSync('./web/mockups.html','utf8'),mockupJs=readFileSync('./web/mockups.js','utf8');assert.match(html,/href="mockups\.html"/);assert.match(mockupHtml,/Playeras y sudaderas/);assert.match(mockupHtml,/Gorras/);assert.match(mockupHtml,/id="mockupCanvas"/);assert.match(mockupJs,/pointerdown/);assert.match(mockupJs,/canvas\.toBlob/);assert.equal((mockupJs.match(/\{id:'[^']+',category:'apparel'/g)||[]).length,5);assert.equal((mockupJs.match(/\{id:'[^']+',category:'caps'/g)||[]).length,3);for(const asset of ['regular-tee','oversized-tee','dryfit-short','dryfit-long','hoodie','trucker-cap','snapback-cap','fitted-cap']){const size=statSync(`./web/assets/mockups/${asset}.webp`).size;assert.ok(size>50_000&&size<300_000,asset+' optimized asset');}
assert.match(mockupHtml,/id="designScale" type="range" min="5" max="600"/);assert.match(mockupHtml,/id="designX" type="range" min="-300" max="300"/);assert.match(mockupJs,/designLayer/);assert.match(mockupJs,/destination-in/);assert.ok(!/roundedRect\(ctx,z\.x-z\.w\/2[\s\S]{0,80}ctx\.clip\(\)/.test(mockupJs));
assert.match(mockupHtml,/PNG, JPG o WebP · hasta 200 MB/);assert.match(mockupHtml,/id="designName">Sin diseño/);assert.match(mockupJs,/MAX_DESIGN_BYTES=200\*1024\*1024/);assert.match(mockupJs,/decodeOptimizedDesign/);assert.match(mockupJs,/MAX_DESIGN_PIXELS=16_000_000/);assert.ok(!mockupJs.includes('sampleDesign'));
assert.match(html,/href="vectorize\.html"/);assert.match(html,/href="analyzer\.html"/);assert.match(html,/href="gang-sheet\.html"/);assert.match(html,/theme\.css/);assert.match(app,/previewStage\.addEventListener\('wheel'/);assert.match(app,/uploadHovered/);assert.match(app,/document\.addEventListener\('paste'/);
const vectorHtml=readFileSync('./web/vectorize.html','utf8'),vectorJs=readFileSync('./web/vectorize.js','utf8');assert.match(vectorHtml,/id="downloadVector"/);assert.match(vectorHtml,/SVG editable/);assert.match(vectorJs,/paletteKmeans/);assert.match(vectorJs,/image\/svg\+xml/);
assert.match(vectorHtml,/id="vectorTrace"/);assert.match(vectorJs,/contourLoops/);assert.match(vectorJs,/pixelPaths/);
const analyzerHtml=readFileSync('./web/analyzer.html','utf8'),analyzerJs=readFileSync('./web/analyzer.js','utf8');assert.match(analyzerHtml,/Detector de semitransparencias|Semitransparencias/);assert.match(analyzerHtml,/Grosor mínimo/);assert.match(analyzerHtml,/Vibrancia/);assert.match(analyzerHtml,/id="autoCorrect"/);assert.ok(!analyzerHtml.includes('id="vibrance"'));assert.match(analyzerJs,/data\[i\]=data\[i\]>=128\?255:0/);assert.match(analyzerJs,/analyzePixels/);assert.match(analyzerJs,/automaticSaturation/);assert.match(analyzerJs,/reinforceDetails/);assert.match(analyzerJs,/await runAnalysis\(\)/);
const sheetHtml=readFileSync('./web/gang-sheet.html','utf8'),sheetJs=readFileSync('./web/gang-sheet.js','utf8');assert.match(sheetHtml,/Ancho \(cm\)<input value="58"/);assert.match(sheetHtml,/max="500"/);assert.match(sheetHtml,/auditor de grosor/i);assert.match(sheetHtml,/id="itemHeight"/);assert.match(sheetHtml,/id="lockRatio"/);assert.match(sheetHtml,/id="applyItemSize"/);assert.match(sheetJs,/CompressionStream\('deflate'\)/);assert.match(sheetJs,/assemblePng/);assert.match(sheetJs,/data\[i\+3\]=255/);assert.match(sheetJs,/cmykRoundTrip/);assert.match(sheetJs,/auditAll/);assert.match(sheetJs,/pointerdown/);assert.match(sheetJs,/applyMeasurements/);assert.match(sheetJs,/addEventListener\('change',applyMeasurements\)/);
const textHtml=readFileSync('./web/text-creator.html','utf8'),textJs=readFileSync('./web/text-creator.js','utf8'),textCss=readFileSync('./web/text-creator.css','utf8');assert.match(textHtml,/Creador de textos/);assert.match(textHtml,/data-preset="graffiti"/);assert.match(textHtml,/data-preset="gothic"/);assert.match(textHtml,/data-effect="gold"/);assert.match(textHtml,/data-effect="chrome"/);assert.match(textHtml,/data-effect="neon"/);assert.match(textHtml,/id="curve"/);assert.match(textJs,/trimmedCanvas/);assert.match(textJs,/createLinearGradient/);assert.match(textJs,/addEventListener\('wheel'/);assert.match(textJs,/\.toBlob/);assert.match(textCss,/@media\(max-width:700px\)/);assert.ok(!html.includes('Muestra de prueba'));assert.ok(!html.includes('id="sample"'));assert.ok(!app.includes('function sample'));
assert.match(textHtml,/id="customFont"/);assert.match(textHtml,/id="downloadTextSvg"/);assert.match(textJs,/PREVIEW_MAX_SIDE/);assert.match(textJs,/FontFace/);assert.match(textJs,/svgDocument/);
const theme=readFileSync('./web/theme.css','utf8'),toolPages=readFileSync('./web/tool-pages.css','utf8');assert.match(theme,/--lab-green:#b8ff3d/);assert.match(theme,/\.toggle input:checked\+span/);assert.match(theme,/\.tool-switcher button\.active/);assert.match(theme,/position:sticky;top:0/);assert.match(toolPages,/grid-auto-columns:78%/);assert.match(toolPages,/\.mobile-only\{display:none\}/);
for(const page of [html,textHtml,mockupHtml,vectorHtml,analyzerHtml,sheetHtml]){assert.match(page,/LZ_STUDIO_TOOLS/);assert.match(page,/id="moduleMenu"/);for(const href of ['index.html','editor.html','text-creator.html','mockups.html','vectorize.html','analyzer.html','gang-sheet.html'])assert.match(page,new RegExp(`href="${href.replace('.','\\.')}"`));}
assert.match(mockupHtml,/id="mockupZoomIn"/);assert.match(vectorHtml,/id="vectorZoomIn"/);assert.match(analyzerHtml,/id="analyzerZoomIn"/);assert.match(sheetHtml,/id="fitSheet"/);assert.match(mockupJs,/addEventListener\('wheel'/);assert.match(vectorJs,/addEventListener\('wheel'/);assert.match(analyzerJs,/addEventListener\('wheel'/);assert.match(sheetJs,/addEventListener\('wheel'/);assert.match(theme,/select option\{background:#fff;color:#111\}/);assert.match(theme,/\.top-modules a\.active/);
const shell=readFileSync('./web/studio-shell.js','utf8');assert.match(shell,/GUÍA RÁPIDA/);assert.match(shell,/Cómo usar esta herramienta/);assert.match(shell,/lz-mobile-switch/);assert.match(shell,/improveNavigation/);assert.match(shell,/setupImageHandoff/);assert.ok(!shell.includes('lzFlow'));for(const source of [html,textHtml,mockupHtml,app,textJs,mockupJs,shell])assert.ok(!/sendMockup|sendTextMockup|latest-design|\?from=/.test(source));for(const moduleJs of [app,textJs,mockupJs,vectorJs,analyzerJs,sheetJs])assert.match(moduleJs,/registerStudioModule/);assert.match(html,/id="cleanupOn"/);assert.match(html,/id="cleanupSize"/);assert.match(app,/cleanupOn/);
console.log('PASS: existing processing, CNN, text creator, mockups, visual lab theme, vectorizer, DTF analyzer and tiled gang-sheet export.');
