import assert from 'node:assert/strict';
import {routedRequest} from './server/vercel-adapter.js';
import {readFile,readdir} from 'node:fs/promises';
const origin='https://www.lzstudiotools.com';
const r=routedRequest(new Request(origin+'/api/site?__lz_path=editor.html&tool=recolor'));
assert.equal(new URL(r.url).pathname,'/editor.html');assert.equal(new URL(r.url).searchParams.get('tool'),'recolor');
const post=routedRequest(new Request(origin+'/api/site?__lz_path=api/account/session',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:'{"access_token":null}'}));
assert.equal(await post.text(),'{"access_token":null}');assert.equal(new URL(post.url).pathname,'/api/account/session');
let blocked=false,enabled=true;
globalThis.fetch=async(url)=>{
 if(url.includes('/auth/v1/user'))return Response.json({id:'test-user'});
 if(url.includes('/rpc/lz_ensure_profile'))return Response.json(null);
 if(url.includes('/lz_profiles'))return Response.json([{id:'test-user',blocked}]);
 if(url.includes('/lz_tools'))return Response.json([{id:'crop',name:'Recortar imagen',enabled},{id:'editor',enabled:true},{id:'recolor',enabled:false}]);
 throw Error('Unexpected upstream request');
};
const {default:app}=await import('./api/site.js');
const req=(path,options={})=>new Request(origin+'/api/site?__lz_path='+encodeURIComponent(path),options);
let response=await app.fetch(req(''));assert.equal(response.status,200);assert.match(await response.text(),/Recortar imagen/);
response=await app.fetch(req('account.html'));assert.equal(response.status,200);const html=await response.text();assert.match(html,/Cambiar contraseña/);assert.doesNotMatch(html,/Recibir enlace de acceso/);
response=await app.fetch(req('crop.html'));assert.equal(response.status,303);assert.equal(response.headers.get('Location'),'/account.html?return=crop.html');
response=await app.fetch(req('crop-app.js'));assert.equal(response.status,401);
const cookie={Cookie:'__Host-lz_session=TEST_TOKEN'};
response=await app.fetch(req('crop.html',{headers:cookie}));assert.equal(response.status,200);assert.match(await response.text(),/Recortar imagen/);
response=await app.fetch(req('crop-app.js',{headers:cookie}));assert.equal(response.status,200);
enabled=false;response=await app.fetch(req('crop.html',{headers:cookie}));assert.equal(response.status,403);enabled=true;
blocked=true;response=await app.fetch(req('crop-app.js',{headers:cookie}));assert.equal(response.status,403);blocked=false;
response=await app.fetch(req('api/account/session',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:'{"access_token":"TEST_TOKEN","remember":false}'}));assert.equal(response.status,200);assert.match(response.headers.get('Set-Cookie'),/HttpOnly; Secure/);assert.doesNotMatch(response.headers.get('Set-Cookie'),/Max-Age/);
response=await app.fetch(req('api/account/session',{method:'POST',headers:{Origin:'https://other.test','Content-Type':'application/json'},body:'{"access_token":null}'}));assert.equal(response.status,403);
response=await app.fetch(req('api/account/session',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:'{"access_token":null}'}));assert.equal(response.status,200);assert.match(response.headers.get('Set-Cookie'),/Max-Age=0/);
response=await app.fetch(req('unknown.html'));assert.equal(response.status,404);
async function files(dir){for(const e of await readdir(dir,{withFileTypes:true})){const p=dir+'/'+e.name;if(e.isDirectory())await files(p);else assert.ok(!/\.(html|js|mjs)$/.test(p),'Tool code must not be static: '+p)}}await files('dist/client');
const config=JSON.parse(await readFile('vercel.json','utf8'));assert.equal(config.outputDirectory,'dist/client');assert.equal(config.buildCommand,'npm run build:vercel');
console.log('PASS: Vercel routing, public home/current password account, protected crop page/scripts, suspension, disabled tools, CSRF, persistent/session cookies, logout and private/static asset separation.');
