import {client,configured,identity,rpc,routes,allowed,safeReturn,syncServerSession,setToolEnabled} from './account-client.js';
import {mountAuth,authError} from './auth-ui.js';
const $=id=>document.getElementById(id);let state=null,busy=false,initializing=true,recovery=new URLSearchParams(location.search).has('recovery');
const message=value=>{$('accountMessage').textContent=value;};
function el(tag,text,className){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;}
const auth=mountAuth($('authContainer'),{onSuccess:async()=>{recovery=false;history.replaceState(null,'','account.html');await load();await returnToTool();},mode:recovery?'update':'login'});
const params=new URLSearchParams(location.search);if(params.has('return'))sessionStorage.setItem('lz-account-return',safeReturn(params.get('return')));
async function returnToTool(){const pending=sessionStorage.getItem('lz-account-return');if(state&&!state.profile?.blocked&&!recovery&&pending&&state.tools.some(t=>(routes[t.id]===pending||(t.id==='editor'&&['editor.html?tool=remove','premium.html'].includes(pending)))&&t.enabled!==false)){sessionStorage.removeItem('lz-account-return');location.replace(safeReturn(pending));}}
async function load(){state=await identity();$('loginPanel').hidden=Boolean(state)&&!recovery;$('memberPanel').hidden=!state||recovery;$('adminPanel').hidden=!state?.isAdmin||recovery;if(!state){message('Inicia sesión o crea una cuenta gratuita.');return;}if(recovery){message('Confirma tu nueva contraseña.');return;}$('memberEmail').textContent=state.user.email;$('memberName').textContent=state.profile?.display_name||'Mi cuenta';$('memberRole').textContent=state.profile?.blocked?'Cuenta suspendida':state.isAdmin?'Administrador':'Cuenta gratuita';const list=$('myTools');list.replaceChildren();for(const tool of state.tools){if(!routes[tool.id]||tool.enabled===false)continue;const card=el('article',undefined,'account-tool');card.append(el('strong',(tool.id==='editor'?'Semitonos / Quitar fondo color':tool.id==='recolor'?'Reemplazar color':tool.name)),el('p',state.profile?.blocked?'Cuenta suspendida':'Gratis · Sin vencimiento'));if(allowed(state,tool.id)){const a=el('a','Abrir herramienta','account-primary');a.href=routes[tool.id];card.append(a);}list.append(card);}$('accessSummary').textContent=state.profile?.blocked?'Acceso suspendido':'Todas las herramientas incluidas';if(state.isAdmin){renderAdmin();await renderStatistics();}message(state.profile?.blocked?'Tu cuenta está suspendida. Comunícate con el administrador.':'Tu cuenta tiene acceso gratuito a todas las herramientas.');}
function renderAdmin(){
 const settings=$('toolSettings');settings.replaceChildren();
 for(const tool of state.tools){if(!routes[tool.id])continue;const row=el('div',undefined,'permission-row');const detail=el('div');detail.append(el('strong',(tool.id==='editor'?'Semitonos / Quitar fondo color':tool.id==='recolor'?'Reemplazar color':tool.name)),el('small',tool.enabled===false?'Desactivada':'Activa'));const toggle=el('button',tool.enabled===false?'Activar':'Desactivar');toggle.type='button';toggle.disabled=busy;toggle.setAttribute('aria-label',(tool.enabled===false?'Activar ':'Desactivar ')+(tool.id==='editor'?'Semitonos / Quitar fondo color':tool.id==='recolor'?'Reemplazar color':tool.name));toggle.onclick=()=>action(()=>setToolEnabled(tool.id,tool.enabled===false));row.append(detail,toggle);settings.append(row);}
 const users=state.profiles;const selector=$('users'),old=selector.value;selector.replaceChildren();for(const user of [...users].sort((a,b)=>a.email.localeCompare(b.email))){const option=el('option',(user.display_name?user.display_name+' · ':'')+user.email+(user.blocked?' · Suspendido':''));option.value=user.id;selector.append(option);}if(users.some(p=>p.id===old))selector.value=old;$('userCount').textContent=String(users.length);$('activeCount').textContent=String(users.filter(p=>!p.blocked).length);$('blockedCount').textContent=String(users.filter(p=>p.blocked).length);selector.onchange=renderUser;renderUser();}
function renderUser(){const user=state.profiles.find(p=>p.id===$('users').value);if(!user)return;$('selectedEmail').textContent=user.email;$('selectedName').textContent=user.display_name||'Sin nombre';$('selectedDate').textContent=user.created_at?new Date(user.created_at).toLocaleDateString('es-MX'):'—';$('blockUser').textContent=user.blocked?'Reactivar cuenta':'Suspender cuenta';$('blockUser').disabled=user.id===state.user.id||busy;$('blockUser').onclick=()=>action(()=>rpc('lz_set_blocked',{target:user.id,value:!user.blocked}));}
async function action(fn){if(busy)return;busy=true;message('Procesando…');try{await fn();await load();}catch(e){message(authError(e));}finally{busy=false;if(state?.isAdmin)renderAdmin();}}
$('signOut').onclick=()=>action(async()=>{const {error}=await client.auth.signOut();if(error)throw error;await syncServerSession(null);});
$('refreshAccount').onclick=()=>action(async()=>{});
$('changePassword').onclick=()=>{recovery=true;auth.setMode('update');$('loginPanel').hidden=false;$('memberPanel').hidden=true;$('adminPanel').hidden=true;message('Elige tu nueva contraseña.');};
if(configured){client.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY'){recovery=true;auth.setMode('update');}setTimeout(async()=>{try{await syncServerSession(session);if(!busy&&!initializing){await load();if(session)await returnToTool();}}catch(e){message(authError(e));}},0);});try{const {data}=await client.auth.getSession();await syncServerSession(data.session);await load();await returnToTool();}catch(e){message(authError(e));}finally{initializing=false;}}else{message('Las cuentas no están disponibles en este momento.');$('loginPanel').hidden=false;initializing=false;}

async function renderStatistics(){const box=$('usageStats');box.textContent='Cargando estadísticas…';try{const stats=await rpc('lz_usage_stats');box.replaceChildren();box.append(el('p',(stats?.users||0)+' usuarios con actividad · últimos 30 días'));const table=el('table'),head=el('tr');for(const label of ['Herramienta','Aperturas','Usuarios','Descargas solicitadas','Errores'])head.append(el('th',label));const thead=el('thead');thead.append(head);table.append(thead);const body=el('tbody');for(const tool of stats?.tools||[]){const row=el('tr');for(const value of [(tool.id==='editor'?'Semitonos / Quitar fondo color':tool.id==='recolor'?'Reemplazar color':tool.name),tool.opens,tool.users,tool.export_requests,tool.errors])row.append(el('td',String(value??0)));body.append(row);}table.append(body);box.append(table);}catch{box.textContent='No se pudieron cargar las estadísticas. Pulsa Actualizar para intentar de nuevo.';}}
