import {client,configured,syncServerSession} from './account-client.js';
import {mountAuth} from './auth-ui.js';
if(!document.querySelector('link[href="account.css"]')){const css=document.createElement('link');css.rel='stylesheet';css.href='account.css';document.head.append(css);}
const nav=document.querySelector('.topbar');
if(nav){
 const button=document.createElement('button');button.type='button';button.className='account-link';button.textContent='Iniciar sesión';button.setAttribute('aria-haspopup','dialog');nav.append(button);
 const dialog=document.createElement('dialog');dialog.className='auth-dialog';dialog.setAttribute('aria-label','Acceso a LZ Studio Tools');dialog.innerHTML='<button class="auth-close" type="button" aria-label="Cerrar">×</button><div class="auth-content"></div>';document.body.append(dialog);dialog.querySelector('.auth-close').onclick=()=>dialog.close();dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close();}});
 let signedIn=false;mountAuth(dialog.querySelector('.auth-content'),{onSuccess:async()=>{const pending=sessionStorage.getItem('lz-account-return');dialog.close();if(pending){sessionStorage.removeItem('lz-account-return');location.href='account.html?return='+encodeURIComponent(pending);}else location.reload();}});
 button.onclick=()=>{if(signedIn)location.href='account.html';else dialog.showModal();};
 const toolPages=['crop.html','editor.html','opacity.html','thickness.html','textures.html','text-creator.html','mockups.html','vectorize.html','analyzer.html','gang-sheet.html','color-enhance.html','upscale.html','extract.html'];
 const current=location.pathname.split('/').pop();
 const update=async session=>{signedIn=Boolean(session);button.textContent=signedIn?'Mi cuenta':'Iniciar sesión';if(configured){try{await syncServerSession(session);}catch{signedIn=false;button.textContent='Iniciar sesión';}}if(!signedIn&&toolPages.includes(current))location.replace('account.html?return='+encodeURIComponent(current+location.search));};
 if(configured){const {data}=await client.auth.getSession();await update(data.session);client.auth.onAuthStateChange((_event,session)=>{setTimeout(()=>update(session),0);});if(toolPages.includes(current))setInterval(async()=>{const {data}=await client.auth.getSession();await update(data.session);},60000);}
 document.addEventListener('click',event=>{const a=event.target.closest('a');if(!a||signedIn||event.ctrlKey||event.metaKey||event.shiftKey||event.altKey)return;const url=new URL(a.href,location.href);const pages=['crop.html','editor.html','opacity.html','thickness.html','textures.html','text-creator.html','mockups.html','vectorize.html','analyzer.html','gang-sheet.html','color-enhance.html','upscale.html','extract.html'];if(url.origin===location.origin&&pages.includes(url.pathname.split('/').pop())){event.preventDefault();sessionStorage.setItem('lz-account-return',url.pathname.split('/').pop()+url.search);dialog.showModal();}});
}
