import {client,routes} from './account-client.js';
import {draftOperation,collectSettings,applySettings,serializeDraft} from '../web/draft-store.js';
import {setupViewport} from '../web/viewport.js';
const make=(tag,text)=>{const node=document.createElement(tag);if(text)node.textContent=text;return node;};
export async function trackTool(id,kind){if(!client||!routes[id])return;try{await client.from('lz_tool_events').insert({tool_id:id,kind});}catch{} }
export async function setupWorkspace(config){
 if(!client)return;const {data}=await client.auth.getSession();const user=data.session?.user;if(!user)return;
 const tool=location.search.includes('tool=recolor')?'recolor':config.id;trackTool(tool,'open');
 const sidebar=document.querySelector('.tools,.lab-sidebar,.mockup-tools,.text-tools');if(!sidebar)return;
 const panel=make('details');panel.className='lz-workspace-options panel';panel.append(make('summary','Mis ajustes y trabajo'));
 const note=make('p','Se guardan en este navegador, para tu cuenta.');note.className='hint';panel.append(note);
 const status=make('p');status.className='hint';status.setAttribute('role','status');const notify=text=>status.textContent=text;
 const key=user.id+':'+config.id,preferenceKey='lz-favorites:'+key,sizeKey='lz-sizes:'+user.id;
 const readJSON=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))||fallback;}catch{return fallback;}};
 const fields=()=>collectSettings();let restoring=false,pendingRecovery=false,timer,saving=false,queued=false,active=true,generation=0;
 client.auth.onAuthStateChange((_event,session)=>{if(session?.user?.id!==user.id){active=false;clearTimeout(timer);}});
 const favorites=make('select');favorites.setAttribute('aria-label','Ajustes favoritos');
 const favoriteName=make('input');favoriteName.placeholder='Nombre del ajuste';favoriteName.maxLength=60;favoriteName.setAttribute('aria-label','Nombre del ajuste favorito');
 const buttons=make('div');buttons.className='lz-options-buttons';const saveFavorite=make('button','Guardar ajuste'),applyFavorite=make('button','Aplicar'),deleteFavorite=make('button','Eliminar');for(const b of [saveFavorite,applyFavorite,deleteFavorite])b.type='button';buttons.append(saveFavorite,applyFavorite,deleteFavorite);
 let favoritesList=readJSON(preferenceKey,[]);const renderFavorites=()=>{favorites.replaceChildren();favorites.append(new Option('Elegir ajuste favorito',''));for(const f of favoritesList)favorites.append(new Option(f.name,f.id));applyFavorite.disabled=deleteFavorite.disabled=favoritesList.length===0;};renderFavorites();
 saveFavorite.onclick=()=>{const name=favoriteName.value.trim();if(!name){notify('Escribe un nombre para el ajuste.');return;}if(favoritesList.length>=20){notify('Puedes guardar hasta 20 ajustes por herramienta. Elimina uno para continuar.');return;}favoritesList.push({id:crypto.randomUUID(),name,settings:fields(),data:config.favoriteState?.()});try{localStorage.setItem(preferenceKey,JSON.stringify(favoritesList));renderFavorites();favoriteName.value='';notify('Ajuste guardado.');}catch{favoritesList.pop();notify('No se pudo guardar el ajuste. Revisa el almacenamiento del navegador.');}};
 applyFavorite.onclick=async()=>{const f=favoritesList.find(f=>f.id===favorites.value);if(!f)return;restoring=true;try{applySettings(f.settings);await config.restoreFavorite?.(f.data);notify('Ajuste aplicado.');}catch{notify('No se pudo aplicar este ajuste.');}finally{restoring=false;schedule();}};
 deleteFavorite.onclick=()=>{favoritesList=favoritesList.filter(f=>f.id!==favorites.value);try{localStorage.setItem(preferenceKey,JSON.stringify(favoritesList));renderFavorites();notify('Ajuste eliminado.');}catch{notify('No se pudo eliminar el ajuste.');}};
 panel.append(favoriteName,buttons,favorites);
 const width=document.querySelector('#widthCm,#effectWidth,#printWidth,#itemWidth,#cropWidth');
 if(width){const sizes=make('select');sizes.className='lz-size-presets';sizes.setAttribute('aria-label','Medidas rápidas de impresión');let custom=readJSON(sizeKey,[]);const render=()=>{sizes.replaceChildren();sizes.append(new Option('Medida rápida · ancho',''));for(const [name,value] of [['Pecho',28],['Espalda',30],['Pecho pequeño',9],['Gorra',7],...custom.map(s=>[s.name,s.width])])sizes.append(new Option(name+' · '+value+' cm',String(value)));};render();width.closest('label').append(sizes);sizes.onchange=()=>{if(!sizes.value)return;width.value=sizes.value;width.dispatchEvent(new Event('input',{bubbles:true}));width.dispatchEvent(new Event('change',{bubbles:true}));sizes.value='';};const name=make('input');name.placeholder='Nombre de mi medida';name.maxLength=40;name.setAttribute('aria-label','Nombre de medida personalizada');const save=make('button','Guardar este ancho');save.type='button';save.onclick=()=>{const value=Number(width.value),title=name.value.trim();if(!title||value<.5||value>100){notify('Escribe un nombre y un ancho de 0.5 a 100 cm.');return;}if(custom.length>=10){notify('Ya tienes 10 medidas.');return;}custom.push({name:title,width:value});try{localStorage.setItem(sizeKey,JSON.stringify(custom));render();name.value='';notify('Medida guardada. El alto conserva la proporción del diseño.');}catch{custom.pop();notify('No se pudo guardar la medida.');}};panel.append(name,save);}
 const saveWork=make('button','Guardar trabajo ahora');saveWork.type='button';const clearWork=make('button','Borrar borrador');clearWork.type='button';panel.append(saveWork,clearWork,status);sidebar.append(panel);
 async function save(){if(!active||restoring||pendingRecovery||!config.getDraft)return;if(saving){queued=true;return;}saving=true;const version=generation;try{const raw=await config.getDraft();if(!raw)return;const draft=await serializeDraft(raw);if(!active||version!==generation)return;await draftOperation(key,{...draft,settings:fields(),version:1});notify('Trabajo guardado · '+new Date().toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit'}));}catch(error){notify(error.message||'No pudimos guardar el borrador. Descarga tu resultado para conservarlo.');}finally{saving=false;if(queued){queued=false;schedule();}}}
 function schedule(){if(restoring||pendingRecovery||!active)return;clearTimeout(timer);timer=setTimeout(save,1600);}
 saveWork.onclick=save;clearWork.onclick=async()=>{generation++;clearTimeout(timer);try{await draftOperation(key,null);notify('Borrador eliminado.');}catch{notify('No se pudo eliminar el borrador.');}};
 try{const draft=await draftOperation(key);if(draft&&draft.version===1){pendingRecovery=true;const notice=make('div');notice.className='lz-recovery';notice.append(make('p','Tienes un trabajo guardado del '+new Date(draft.updatedAt).toLocaleString('es-MX')+'.'));const recover=make('button','Recuperar'),discard=make('button','Descartar');recover.type=discard.type='button';notice.append(recover,discard);sidebar.prepend(notice);recover.onclick=async()=>{restoring=true;recover.disabled=discard.disabled=true;try{applySettings(draft.settings);await config.restoreDraft?.(draft);applySettings(draft.settings,document,false);await config.afterRestore?.(draft);pendingRecovery=false;notice.remove();notify('Trabajo recuperado.');}catch{notify('No se pudo recuperar el trabajo. El borrador sigue guardado.');recover.disabled=discard.disabled=false;}finally{restoring=false;}};discard.onclick=async()=>{try{await draftOperation(key,null);pendingRecovery=false;notice.remove();notify('Puedes comenzar un trabajo nuevo.');}catch{notify('No se pudo descartar el trabajo.');}};}}
 catch{notify('El navegador no permite recuperar borradores.');}
 const change=event=>{if(event.target.closest('dialog,.lz-workspace-options,.lz-recovery'))return;if(pendingRecovery&&event.target.type==='file'){notify('Recupera o descarta el trabajo anterior antes de guardar este nuevo trabajo.');}schedule();};
 document.addEventListener('input',change);document.addEventListener('change',change);document.addEventListener('pointerup',change);document.addEventListener('click',event=>{change(event);if(event.target.closest('button[id^="download"]:not(:disabled)'))trackTool(tool,'export');});document.addEventListener('lz-work-changed',schedule);window.addEventListener('pagehide',()=>{clearTimeout(timer);save();});
 let errorReported=false;window.addEventListener('error',()=>{if(!errorReported){errorReported=true;trackTool(tool,'error');}});window.addEventListener('unhandledrejection',()=>{if(!errorReported){errorReported=true;trackTool(tool,'error');}});
 if(config.getComparison)setupComparison(config);
}
function setupComparison(config){
 const toolbar=document.querySelector('.canvas-toolbar,.lab-toolbar,.text-toolbar,.mockup-toolbar');if(!toolbar)return;
 const open=make('button','Comparar antes / después');open.type='button';toolbar.append(open);
 const dialog=make('dialog');dialog.className='lz-compare-dialog';dialog.setAttribute('aria-label','Comparar antes y después');const title=make('h2','Antes / Después'),close=make('button','Cerrar');close.type='button';const zoomControls=make('div');zoomControls.className='zoom-controls';const wrap=make('div');wrap.className='lz-compare-wrap checker';const canvas=make('canvas');wrap.append(canvas);const slider=make('input');slider.type='range';slider.min=0;slider.max=100;slider.value=50;slider.setAttribute('aria-label','División entre original y resultado');const labels=make('p','Original a la izquierda · Resultado a la derecha');const actions=make('div');actions.className='lz-options-buttons';actions.append(close,zoomControls);dialog.append(title,actions,labels,wrap,slider);document.body.append(dialog);let images,zoom=1;
 const fit=()=>{zoom=Math.min((wrap.clientWidth-24)/canvas.width,(wrap.clientHeight-24)/canvas.height);layout();};const layout=()=>{canvas.style.width=canvas.width*zoom+'px';canvas.style.height=canvas.height*zoom+'px';};
 function draw(){if(!images)return;const [before,after]=images,ratio=Math.min(1,1400/Math.max(after.width||after.naturalWidth,after.height||after.naturalHeight));canvas.width=Math.max(1,Math.round((after.width||after.naturalWidth)*ratio));canvas.height=Math.max(1,Math.round((after.height||after.naturalHeight)*ratio));const x=canvas.width*Number(slider.value)/100,ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(after,0,0,canvas.width,canvas.height);ctx.save();ctx.beginPath();ctx.rect(0,0,x,canvas.height);ctx.clip();ctx.clearRect(0,0,x,canvas.height);ctx.drawImage(before,0,0,canvas.width,canvas.height);ctx.restore();ctx.strokeStyle='#b8ff3d';ctx.lineWidth=2/Math.max(.1,zoom);ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,canvas.height);ctx.stroke();layout();}
 open.onclick=async()=>{try{images=await config.getComparison();if(!images?.[0]||!images?.[1]){open.textContent='Primero prepara un resultado';setTimeout(()=>open.textContent='Comparar antes / después',2000);return;}draw();dialog.showModal();fit();}catch{open.textContent='Comparación no disponible';}};close.onclick=()=>dialog.close();slider.oninput=draw;
 setupViewport({wrap,controls:zoomControls,onZoom:factor=>{zoom=Math.max(.02,Math.min(8,zoom*factor));layout();},onFit:fit,zoomButtons:true});new ResizeObserver(()=>{if(dialog.open)layout();}).observe(wrap);
}
