import {client,routes} from './account-client.js';
import {draftOperation,collectSettings,applySettings,serializeDraft} from '../web/draft-store.js';
import {setupViewport} from '../web/viewport.js';
const make=(tag,text)=>{const node=document.createElement(tag);if(text)node.textContent=text;return node;};
export async function trackTool(id,kind){id=['remove','premium'].includes(id)?'editor':id;if(!client||!routes[id])return;try{await client.from('lz_tool_events').insert({tool_id:id,kind});}catch{}}
export async function setupWorkspace(config){
 if(!client)return;const {data}=await client.auth.getSession();const user=data.session?.user;if(!user)return;trackTool(config.id,'open');
 const sidebar=document.querySelector('.tools,.lab-sidebar,.mockup-tools,.text-tools');if(!sidebar)return;
 const panel=make('section');panel.className='lz-workspace-options panel';panel.append(make('h2','Mi espacio de trabajo'));
 const note=make('p','Guarda tus ajustes y retoma este trabajo en este navegador.');note.className='hint';panel.append(note);
 const status=make('p','Sin borrador guardado todavía.');status.className='lz-save-status';status.setAttribute('role','status');status.setAttribute('aria-live','polite');const notify=text=>status.textContent=text;
 const key=user.id+':'+config.id,preferenceKey='lz-favorites:'+key,sizeKey='lz-sizes:'+user.id;
 const readJSON=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))||fallback;}catch{return fallback;}};
 let restoring=false,pendingRecovery=false,timer,saving=false,queued=false,active=true,generation=0,discarded=false;
 const fields=()=>collectSettings();
 client.auth.onAuthStateChange((_event,session)=>{if(session?.user?.id!==user.id){active=false;clearTimeout(timer);}});
 function group(title,copy){const d=make('details');d.className='lz-workspace-group';d.append(make('summary',title));const hint=make('p',copy);hint.className='hint';d.append(hint);panel.append(d);return d;}
 function label(text,field){const node=make('label',text);node.append(field);return node;}
 function button(text){const b=make('button',text);b.type='button';return b;}
 const work=group('Trabajo actual','El borrador incluye la imagen y los cambios. Puedes recuperarlo cuando vuelvas a esta herramienta.');work.open=true;
 const automatic=make('input');automatic.type='checkbox';automatic.checked=readJSON('lz-autosave:'+key,true);automatic.setAttribute('aria-label','Guardar borrador automáticamente');const autoLabel=label(' Guardar automáticamente',automatic);autoLabel.className='check';work.append(autoLabel);
 const saveWork=button('Guardar borrador'),clearWork=button('Eliminar borrador');const workButtons=make('div');workButtons.className='lz-options-buttons';workButtons.append(saveWork,clearWork);work.append(status,workButtons);
 const favoritesGroup=group('Ajustes favoritos','Guarda los valores de esta herramienta para aplicarlos a otro diseño. No incluye la imagen.');
 const favorites=make('select');favorites.setAttribute('aria-label','Ajuste guardado');
 const favoriteName=make('input');favoriteName.placeholder='Ej. Trama para playera negra';favoriteName.maxLength=60;
 const saveFavorite=button('Guardar ajustes'),applyFavorite=button('Aplicar ajuste'),deleteFavorite=button('Eliminar ajuste');
 let favoritesList=readJSON(preferenceKey,[]);
 function selection(){const valid=favoritesList.some(f=>f.id===favorites.value);applyFavorite.disabled=deleteFavorite.disabled=!valid;}
 function renderFavorites(selected=''){favorites.replaceChildren(new Option(favoritesList.length?'Selecciona un ajuste':'Todavía no hay ajustes guardados',''));for(const f of favoritesList)favorites.append(new Option(f.name,f.id));favorites.value=selected;selection();}renderFavorites();favorites.onchange=selection;
 const favoriteButtons=make('div');favoriteButtons.className='lz-options-buttons';favoriteButtons.append(applyFavorite,deleteFavorite);
 favoritesGroup.append(label('Aplicar ajustes guardados',favorites),favoriteButtons,label('Nombre del nuevo ajuste',favoriteName),saveFavorite);
 saveFavorite.onclick=()=>{const name=favoriteName.value.trim();if(!name){favoriteName.focus();notify('Escribe un nombre para guardar los ajustes.');return;}const existing=favoritesList.find(f=>f.name.toLowerCase()===name.toLowerCase());if(!existing&&favoritesList.length>=20){notify('Ya tienes 20 ajustes. Elimina uno para guardar otro.');return;}const entry={id:existing?.id||crypto.randomUUID(),name,settings:fields(),data:config.favoriteState?.()},next=existing?favoritesList.map(f=>f.id===existing.id?entry:f):[...favoritesList,entry];try{localStorage.setItem(preferenceKey,JSON.stringify(next));favoritesList=next;renderFavorites(entry.id);favoriteName.value='';notify('Ajustes «'+name+'» guardados.');}catch{notify('No se pudieron guardar los ajustes. Revisa el espacio del navegador.');}};
 applyFavorite.onclick=async()=>{const f=favoritesList.find(f=>f.id===favorites.value);if(!f)return;restoring=true;try{applySettings(f.settings);await config.restoreFavorite?.(f.data);notify('Ajustes «'+f.name+'» aplicados.');}catch{notify('No se pudieron aplicar estos ajustes.');}finally{restoring=false;schedule();}};
 deleteFavorite.onclick=()=>{const f=favoritesList.find(f=>f.id===favorites.value);if(!f||!confirm('¿Eliminar el ajuste «'+f.name+'»?'))return;const next=favoritesList.filter(item=>item.id!==f.id);try{localStorage.setItem(preferenceKey,JSON.stringify(next));favoritesList=next;renderFavorites();notify('Ajuste eliminado.');}catch{notify('No se pudo eliminar el ajuste.');}};
 const width=document.querySelector('#widthCm,#effectWidth,#printWidth,#itemWidth,#cropWidth');
 if(width){const sizesGroup=group('Mis medidas','Guarda un ancho que uses seguido. El alto se calcula según la proporción de cada diseño.');let custom=readJSON(sizeKey,[]);
  const sizes=make('select');sizes.setAttribute('aria-label','Ancho de impresión guardado');
  function renderSizes(){sizes.replaceChildren(new Option('Selecciona una medida',''));for(const [name,value] of [['Pecho',28],['Espalda',30],['Pecho pequeño',9],['Gorra',7],...custom.map(s=>[s.name,s.width])])sizes.append(new Option(name+' · '+value+' cm',String(value)));}renderSizes();
  const applySize=button('Usar medida');applySize.onclick=()=>{if(!sizes.value){notify('Selecciona la medida que quieres usar.');return;}if(Number(sizes.value)>Number(width.max||500)){notify('Esta medida supera el ancho de esta herramienta.');return;}width.value=sizes.value;width.dispatchEvent(new Event('input',{bubbles:true}));width.dispatchEvent(new Event('change',{bubbles:true}));notify('Medida aplicada: '+sizes.value+' cm de ancho.');};
  const name=make('input');name.placeholder='Ej. Frente adulto';name.maxLength=40;const save=button('Guardar ancho actual'),removeSize=button('Eliminar mi medida');
  save.onclick=()=>{const value=Number(width.value),title=name.value.trim();if(!title||!Number.isFinite(value)||value<.5||value>500){notify('Escribe un nombre y usa un ancho válido.');return;}const existing=custom.find(s=>s.name.toLowerCase()===title.toLowerCase());if(!existing&&custom.length>=10){notify('Ya tienes 10 medidas. Elimina una para guardar otra.');return;}const next=existing?custom.map(s=>s===existing?{name:title,width:value}:s):[...custom,{name:title,width:value}];try{localStorage.setItem(sizeKey,JSON.stringify(next));custom=next;renderSizes();name.value='';notify('Medida «'+title+'» guardada.');}catch{notify('No se pudo guardar la medida.');}};
  removeSize.onclick=()=>{const entry=custom.find(s=>String(s.width)===sizes.value);if(!entry){notify('Solo puedes eliminar tus medidas personalizadas.');return;}if(!confirm('¿Eliminar la medida «'+entry.name+'»?'))return;const next=custom.filter(s=>s!==entry);try{localStorage.setItem(sizeKey,JSON.stringify(next));custom=next;renderSizes();notify('Medida eliminada.');}catch{notify('No se pudo eliminar la medida.');}};
  sizesGroup.append(label('Anchos frecuentes',sizes),applySize,label('Nombre de mi medida',name),save,removeSize);
 }
 sidebar.append(panel);
 async function save(manual=false){if(!active||restoring||pendingRecovery||!config.getDraft){if(manual&&pendingRecovery)notify('Recupera o descarta el borrador anterior primero.');return;}if(saving){queued=true;return;}saving=true;saveWork.disabled=true;const version=generation;try{const raw=await config.getDraft();if(!raw){if(manual)notify('Carga una imagen o crea un diseño antes de guardar.');return;}notify('Guardando borrador…');const draftSettings=fields(),draft=await serializeDraft(raw);if(!active||version!==generation)return;await draftOperation(key,{...draft,settings:draftSettings,version:1});discarded=false;clearWork.disabled=false;notify('Borrador guardado · '+new Date().toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit'}));}catch(error){notify(error.message||'No se pudo guardar. Descarga el resultado para conservarlo.');}finally{saving=false;saveWork.disabled=false;if(queued){queued=false;schedule();}}}
 function schedule(){if(restoring||pendingRecovery||!active||!automatic.checked)return;discarded=false;clearTimeout(timer);timer=setTimeout(()=>save(),3000);}
 automatic.onchange=()=>{try{localStorage.setItem('lz-autosave:'+key,JSON.stringify(automatic.checked));}catch{}clearTimeout(timer);if(automatic.checked){discarded=false;schedule();}notify(automatic.checked?'Guardado automático activado.':'Guardado automático desactivado. Puedes guardar con el botón.');};
 saveWork.onclick=()=>save(true);clearWork.disabled=true;clearWork.onclick=async()=>{if(!confirm('¿Eliminar el borrador guardado? El diseño abierto seguirá en pantalla.'))return;generation++;discarded=true;clearTimeout(timer);try{await draftOperation(key,null);clearWork.disabled=true;notify('Borrador eliminado. Se volverá a guardar cuando hagas un cambio.');}catch{notify('No se pudo eliminar el borrador.');}};
 try{const draft=await draftOperation(key);if(draft&&draft.version===1){pendingRecovery=true;clearWork.disabled=true;const notice=make('div');notice.className='lz-recovery';notice.append(make('h3','Retomar trabajo anterior'),make('p',new Date(draft.updatedAt).toLocaleString('es-MX')));const recover=button('Recuperar trabajo'),discard=button('Empezar uno nuevo');notice.append(recover,discard);sidebar.prepend(notice);notify('Hay un borrador disponible para recuperar.');recover.onclick=async()=>{restoring=true;recover.disabled=discard.disabled=true;try{applySettings(draft.settings);await config.restoreDraft?.(draft);applySettings(draft.settings,document,false);await config.afterRestore?.(draft);pendingRecovery=false;clearWork.disabled=false;notice.remove();notify('Trabajo recuperado. Puedes seguir editando.');}catch{notify('No se pudo recuperar. El borrador sigue guardado.');recover.disabled=discard.disabled=false;}finally{restoring=false;}};discard.onclick=async()=>{try{generation++;await draftOperation(key,null);pendingRecovery=false;notice.remove();clearWork.disabled=true;notify('Listo para un trabajo nuevo.');}catch{notify('No se pudo eliminar el borrador anterior.');}};}}
 catch{notify('El navegador no permite recuperar borradores.');}
 const change=event=>{if(event.target.closest('dialog,.lz-workspace-options,.lz-recovery,.zoom-controls,.lab-toolbar,.lz-preview-actions,.lz-mobile-switch'))return;schedule();};
 document.addEventListener('input',change);document.addEventListener('change',change);document.addEventListener('pointerup',change);document.addEventListener('lz-work-changed',schedule);window.addEventListener('pagehide',()=>{clearTimeout(timer);if(automatic.checked&&!discarded)save();});
 let errorReported=false;window.addEventListener('error',()=>{if(!errorReported){errorReported=true;trackTool(config.id,'error');}});window.addEventListener('unhandledrejection',()=>{if(!errorReported){errorReported=true;trackTool(config.id,'error');}});
 if(config.getComparison)setupComparison(config);
}
function setupComparison(config){
 const toolbar=document.querySelector('.canvas-toolbar,.lab-toolbar,.text-toolbar,.mockup-toolbar');if(!toolbar)return;
 const open=make('button','Comparar antes / después');open.type='button';toolbar.append(open);
 const dialog=make('dialog');dialog.className='lz-compare-dialog';dialog.setAttribute('aria-label','Comparar antes y después');const title=make('h2','Antes / Después'),close=make('button','Cerrar');close.type='button';const zoomControls=make('div');zoomControls.className='zoom-controls';const wrap=make('div');wrap.className='lz-compare-wrap checker';const canvas=make('canvas');wrap.append(canvas);const slider=make('input');slider.type='range';slider.min=0;slider.max=100;slider.value=50;slider.setAttribute('aria-label','División entre original y resultado');const labels=make('p','Original a la izquierda · Resultado a la derecha');const actions=make('div');actions.className='lz-options-buttons';actions.append(close,zoomControls);dialog.append(title,actions,labels,wrap,slider);document.body.append(dialog);let images,zoom=1;
 const fit=()=>{zoom=Math.min((wrap.clientWidth-24)/canvas.width,(wrap.clientHeight-24)/canvas.height);layout();};const layout=()=>{canvas.style.width=canvas.width*zoom+'px';canvas.style.height=canvas.height*zoom+'px';};
 function draw(){if(!images)return;const [before,after]=images,ratio=Math.min(1,1400/Math.max(after.width||after.naturalWidth,after.height||after.naturalHeight));canvas.width=Math.max(1,Math.round((after.width||after.naturalWidth)*ratio));canvas.height=Math.max(1,Math.round((after.height||after.naturalHeight)*ratio));const x=canvas.width*Number(slider.value)/100,ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(after,0,0,canvas.width,canvas.height);ctx.save();ctx.beginPath();ctx.rect(0,0,x,canvas.height);ctx.clip();ctx.clearRect(0,0,x,canvas.height);ctx.drawImage(before,0,0,canvas.width,canvas.height);ctx.restore();ctx.strokeStyle='#b8ff3d';ctx.lineWidth=2/Math.max(.1,zoom);ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,canvas.height);ctx.stroke();layout();}
 open.onclick=async()=>{try{images=await config.getComparison();if(!images?.[0]||!images?.[1]){open.textContent='Primero prepara un resultado';setTimeout(()=>open.textContent='Comparar antes / después',2000);return;}draw();dialog.showModal();fit();}catch{open.textContent='Comparación no disponible';}};close.onclick=()=>dialog.close();slider.oninput=draw;
 setupViewport({wrap,controls:zoomControls,onZoom:factor=>{zoom=Math.max(.02,Math.min(8,zoom*factor));layout();},onFit:fit,zoomButtons:true});new ResizeObserver(()=>{if(dialog.open)layout();}).observe(wrap);
}
