import {canvasArtifact,processedArtifact,requireTransferImage} from './transfer-export.js';
import {registerStudioModule} from './studio-shell.js';
const $=id=>document.getElementById(id);let bitmap=null,original=null,working=null,fileName='diseno-dtf',showOriginal=false,lastReport=null,lastCorrection=null,analyzerZoom=1,analyzerFit=true;
function status(message,error=false){$('analyzerStatus').textContent=message;$('analyzerStatus').classList.toggle('error',error)}
function menu(open){$('moduleMenu').hidden=!open;$('menuBackdrop').hidden=!open;$('menuButton').setAttribute('aria-expanded',String(open))}$('menuButton').onclick=()=>menu($('moduleMenu').hidden);$('menuClose').onclick=()=>menu(false);$('menuBackdrop').onclick=()=>menu(false);document.addEventListener('keydown',e=>{if(e.key==='Escape')menu(false)});
function createCanvas(w,h){const c=document.createElement('canvas');c.width=w;c.height=h;return c}
function cloneCanvas(source){const c=createCanvas(source.width,source.height);c.getContext('2d').drawImage(source,0,0);return c}
function layoutAnalyzer(){const c=$('analyzerCanvas');if(c.hidden||!c.width)return;const wrap=document.querySelector('.lab-canvas-wrap'),fit=Math.min((wrap.clientWidth-20)/c.width,(wrap.clientHeight-20)/c.height),scale=Math.max(.04,Math.min(5,analyzerFit?fit:analyzerZoom));c.style.width=c.width*scale+'px';c.style.height=c.height*scale+'px';$('analyzerZoomLabel').textContent=analyzerFit?'Ajustar':Math.round(scale*100)+' %';if(analyzerFit)analyzerZoom=scale}
function show(){if(globalThis.Event)document.dispatchEvent?.(new Event('lz-work-changed'));if(!working)return;const src=showOriginal?original:working,c=$('analyzerCanvas'),scale=Math.min(1,1100/Math.max(src.width,src.height));c.width=Math.max(1,Math.round(src.width*scale));c.height=Math.max(1,Math.round(src.height*scale));c.getContext('2d').drawImage(src,0,0,c.width,c.height);c.hidden=false;$('analyzerEmpty').hidden=true;$('showAnalyzed').classList.toggle('active',!showOriginal);$('showAnalyzerOriginal').classList.toggle('active',showOriginal);requestAnimationFrame(layoutAnalyzer)}
async function upload(file){if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>40*1024*1024){status('Usa PNG, JPG o WebP de hasta 40 MB.',true);return}try{bitmap?.close?.();bitmap=await createImageBitmap(file,{imageOrientation:'from-image'});if(bitmap.width*bitmap.height>24e6)throw Error('El archivo supera 24 MP. Redúcelo antes de auditarlo.');original=createCanvas(bitmap.width,bitmap.height);original.getContext('2d').drawImage(bitmap,0,0);working=cloneCanvas(original);lastCorrection=null;fileName=file.name.replace(/\.[^.]+$/,'');$('analyzerName').textContent=file.name;$('analyzerSize').textContent=`${bitmap.width} × ${bitmap.height} px`;$('runAnalysis').disabled=false;$('autoCorrect').disabled=false;$('downloadAnalyzed').disabled=false;$('analysisSummary').textContent='Analizando sin modificar tu imagen…';showOriginal=false;show();await runAnalysis();return true;}catch(error){status(error.message||'No se pudo abrir esa imagen.',true)}finally{$('analyzerFile').value=''}}
$('analyzerFile').onchange=()=>upload($('analyzerFile').files[0]);
function saturation(r,g,b){const max=Math.max(r,g,b),min=Math.min(r,g,b);return max?((max-min)/max)*100:0}
function analysisCanvas(source){const scale=Math.min(1,1400/Math.max(source.width,source.height)),c=createCanvas(Math.max(1,Math.round(source.width*scale)),Math.max(1,Math.round(source.height*scale)));c.getContext('2d',{willReadFrequently:true}).drawImage(source,0,0,c.width,c.height);return c}
function analyzePixels(source=working){const c=analysisCanvas(source),ctx=c.getContext('2d',{willReadFrequently:true}),data=ctx.getImageData(0,0,c.width,c.height).data,total=c.width*c.height,dist=new Uint16Array(total),inf=65535;let semi=0,solid=0,sat=0;for(let p=0;p<total;p++){const i=p*4,a=data[i+3];if(a>0&&a<255)semi++;if(a>=128){solid++;sat+=saturation(data[i],data[i+1],data[i+2]);dist[p]=inf}else dist[p]=0}for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++){const p=y*c.width+x;if(!dist[p])continue;let d=dist[p];if(x)d=Math.min(d,dist[p-1]+1);if(y)d=Math.min(d,dist[p-c.width]+1);dist[p]=d}for(let y=c.height-1;y>=0;y--)for(let x=c.width-1;x>=0;x--){const p=y*c.width+x;if(!dist[p])continue;let d=dist[p];if(x<c.width-1)d=Math.min(d,dist[p+1]+1);if(y<c.height-1)d=Math.min(d,dist[p+c.width]+1);dist[p]=d}const widthCm=Math.max(1,Number($('printWidth').value)||28),minMm=Number($('minimumThickness').value),pxPerMm=c.width/(widthCm*10),radius=Math.max(1,minMm*pxPerMm/2);let thin=0;for(let p=0;p<total;p++)if(dist[p]&&dist[p]<radius)thin++;return {semi,semiPct:semi/total*100,solid,thin,thinPct:solid?thin/solid*100:0,saturation:solid?sat/solid:0,width:c.width,height:c.height,minMm}}
function setMetric(id,value,bad){const el=$(id);el.querySelector('strong').textContent=value;el.classList.toggle('bad',bad);el.classList.toggle('good',!bad)}
function renderReport(report,correction=lastCorrection){setMetric('alphaMetric',report.semi?`${report.semiPct.toFixed(2)} %`:'0 %',report.semi>0);setMetric('thinMetric',correction?.radius?`+${correction.radius} px`:`${report.thinPct.toFixed(1)} %`,report.thinPct>18&&!correction?.radius);setMetric('colorMetric',`${report.saturation.toFixed(0)} %`,report.saturation<28&&!correction);const rows=[{bad:report.semi>0,title:'Detector de semitransparencias',text:report.semi?`${report.semi.toLocaleString()} píxeles todavía necesitan corrección.`:'Alfa limpio: solo píxeles sólidos o transparentes.'},{bad:report.thinPct>18&&!correction?.radius,title:'Auditor de grosor',text:correction?.radius?`Se reforzaron los contornos ${correction.radius} px para proteger detalles diminutos.`:report.thinPct>18?`Hay zonas debajo de ${report.minMm} mm.`:`El grosor se ve estable para ${report.minMm} mm.`},{bad:false,title:'Vibrancia automática',text:correction?`Vibrancia ajustada ${correction.amount} puntos.`:'Análisis de color terminado.'}];$('auditList').innerHTML=rows.map(row=>`<div class="audit-row ${row.bad?'bad':'good'}"><span class="audit-icon">${row.bad?'!':'✓'}</span><b>${row.title}</b><small>${row.text}</small></div>`).join('');$('analysisSummary').textContent=correction?'Corrección automática aplicada · compara con el original':rows.some(row=>row.bad)?'Auditoría terminada · revisa las advertencias':'Auditoría terminada · archivo listo'}
async function runAnalysis(){if(!working)return;$('analyzerBusy').hidden=false;await new Promise(requestAnimationFrame);try{lastCorrection=null;lastReport=analyzePixels(working);renderReport(lastReport,null);status('Auditoría completada sin modificar la imagen.')}catch{status('No se pudo completar la auditoría.',true)}finally{$('analyzerBusy').hidden=true}}
function solidAlpha(canvas){const context=canvas.getContext('2d',{willReadFrequently:true}),image=context.getImageData(0,0,canvas.width,canvas.height),data=image.data;for(let i=3;i<data.length;i+=4)data[i]=data[i]>=128?255:0;context.putImageData(image,0,0)}
function automaticSaturation(canvas,current){const amount=current<22?30:current<35?22:current<50?14:8,context=canvas.getContext('2d',{willReadFrequently:true}),image=context.getImageData(0,0,canvas.width,canvas.height),data=image.data,f=amount/100;for(let i=0;i<data.length;i+=4){if(!data[i+3])continue;const avg=(data[i]+data[i+1]+data[i+2])/3;data[i]=Math.max(0,Math.min(255,data[i]+(data[i]-avg)*f));data[i+1]=Math.max(0,Math.min(255,data[i+1]+(data[i+1]-avg)*f));data[i+2]=Math.max(0,Math.min(255,data[i+2]+(data[i+2]-avg)*f))}context.putImageData(image,0,0);return amount}
function reinforceDetails(canvas,thinPct){if(thinPct<4)return {canvas,radius:0};const pxPerMm=canvas.width/(Math.max(1,Number($('printWidth').value)||28)*10),target=Math.max(1,Math.min(5,Math.ceil(Number($('minimumThickness').value)*pxPerMm/2))),out=createCanvas(canvas.width,canvas.height),context=out.getContext('2d'),steps=[...new Set([1,Math.ceil(target/2),target])];for(const distance of steps)for(const [dx,dy] of [[-distance,0],[distance,0],[0,-distance],[0,distance],[-distance,-distance],[distance,-distance],[-distance,distance],[distance,distance]])context.drawImage(canvas,dx,dy);context.drawImage(canvas,0,0);return {canvas:out,radius:target}}
async function autoCorrect(){if(!original)return;if(!['correctAlpha','correctThickness','correctColor'].some(id=>$(id).checked)){status('Elige al menos una corrección. Tu original sigue intacto.');return;}$('analyzerBusy').hidden=false;$('autoCorrect').disabled=true;await new Promise(requestAnimationFrame);try{const before=analyzePixels(original);working=cloneCanvas(original);if($('correctAlpha').checked)solidAlpha(working);const amount=$('correctColor').checked?automaticSaturation(working,before.saturation):0,reinforced=$('correctThickness').checked?reinforceDetails(working,before.thinPct):{canvas:working,radius:0};working=reinforced.canvas;lastCorrection={amount,radius:reinforced.radius,semi:before.semi};lastReport=analyzePixels(working);showOriginal=false;show();renderReport(lastReport,lastCorrection);status(`Correcciones aplicadas: vibrancia +${amount}${reinforced.radius?` y detalles reforzados ${reinforced.radius} px`:''}.`)}catch(error){status(error.message||'No se pudo aplicar la corrección automática.',true)}finally{$('analyzerBusy').hidden=true;$('autoCorrect').disabled=false}}
$('runAnalysis').onclick=runAnalysis;$('autoCorrect').onclick=autoCorrect;$('showAnalyzed').onclick=()=>{showOriginal=false;show()};$('showAnalyzerOriginal').onclick=()=>{showOriginal=true;show()};$('printWidth').onchange=()=>{if(original)runAnalysis()};$('minimumThickness').onchange=()=>{if(original)runAnalysis()};
$('analyzerZoomIn').onclick=()=>{analyzerFit=false;analyzerZoom=Math.min(5,analyzerZoom*1.25);layoutAnalyzer()};$('analyzerZoomOut').onclick=()=>{analyzerFit=false;analyzerZoom=Math.max(.04,analyzerZoom/1.25);layoutAnalyzer()};$('analyzerFit').onclick=()=>{analyzerFit=true;layoutAnalyzer()};const analyzerWrap=document.querySelector('.lab-canvas-wrap');analyzerWrap.addEventListener('wheel',event=>{if(!working)return;event.preventDefault();analyzerFit=false;analyzerZoom=Math.max(.04,Math.min(5,analyzerZoom*(event.deltaY<0?1.14:1/1.14)));layoutAnalyzer()},{passive:false});new ResizeObserver(()=>{if(analyzerFit)layoutAnalyzer()}).observe(analyzerWrap);
$('downloadAnalyzed').onclick=()=>{if(!working)return;working.toBlob(blob=>{if(!blob){status('No se pudo preparar el PNG.',true);return}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=fileName.replace(/[^a-z0-9áéíóúñ_-]/gi,'_')+'_DTF_corregido.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);status('PNG corregido descargado.')},'image/png')};
registerStudioModule({id:'analyzer',onFit:()=>{analyzerFit=true;layoutAnalyzer();},getComparison:()=>[original,working],getDraft:()=>original?{images:{original,working},data:{fileName,lastCorrection}}:null,restoreDraft:async d=>{await upload(new File([d.images.original],d.data.fileName,{type:'image/png'}));if(d.images.working){const restored=await createImageBitmap(d.images.working);working=cloneCanvas(restored);restored.close();}lastCorrection=d.data.lastCorrection;},afterRestore:()=>{showOriginal=false;show();lastReport=analyzePixels(working);renderReport(lastReport,lastCorrection);},onZoom:factor=>{if(!working)return;analyzerFit=false;analyzerZoom=Math.max(.04,Math.min(5,analyzerZoom*factor));layoutAnalyzer();},exportCurrent:async()=>{requireTransferImage(working,!$('analyzerBusy').hidden);return canvasArtifact(working,fileName+'_DTF_corregido.png',working.width/Number($('printWidth').value)*2.54,Number($('printWidth').value))},importCurrent:async(blob,name)=>upload(new File([blob],name,{type:blob.type}))});
