import {canvasArtifact,processedArtifact,requireTransferImage} from './transfer-export.js';
import {registerStudioModule} from './studio-shell.js';
import {exportTiledPng} from './exporter.js';
import {COLOR_DEFAULTS,COLOR_STYLES,autoColorAdjustments} from './color-engine.js';
const $=id=>document.getElementById(id);
let source=null,previewSource=null,result=null,fileName='diseno',zoom=1,fit=true,originalView=false,worker=null,revision=0,loadRevision=0,timer,exporting=false,loading=false;
const canvas=$('effectCanvas'),wrap=document.querySelector('.lab-canvas-wrap');
function status(message,error=false){$('effectStatus').textContent=message;$('effectStatus').classList.toggle('error',error)}
function params(){const colorAdjustments={};for(const key of Object.keys(COLOR_DEFAULTS))colorAdjustments[key]=Number($('color_'+key).value);return {effectTool:'color',widthCm:Number($('effectWidth').value),colorAspect:source?source.width/source.height:1,colorAdjustments}}
function dimensions(p=params()){const dpi=Number($('effectDpi').value),width=Math.round(p.widthCm/2.54*dpi),height=source?Math.round(width*source.height/source.width):0;if(!Number.isFinite(p.widthCm)||p.widthCm<.5||p.widthCm>100)throw Error('Indica un ancho entre 0.5 y 100 cm.');if(width*height>140e6||Math.max(width,height)>24000)throw Error('Reduce la medida o la resolución: máximo 140 MP y 24,000 px por lado.');return {width,height,dpi}}
function sizeInfo(){$('effectFile').disabled=exporting||loading;try{const d=dimensions();$('effectHeight').value=source?(params().widthCm*source.height/source.width).toFixed(2):'';$('effectPixels').textContent=source?`${d.width.toLocaleString()} × ${d.height.toLocaleString()} px · ${d.dpi} ppp`:'';$('downloadEffect').disabled=!source||exporting||loading;$('autoColor').disabled=$('resetColors').disabled=!source||exporting||loading;$('colorControls').disabled=!source}catch(error){$('downloadEffect').disabled=true;status(error.message,true)}}
function outputs(){for(const key of Object.keys(COLOR_DEFAULTS))$('color_'+key+'Out').value=$('color_'+key).value+(key==='exposure'?' EV':'')}
function writeAdjustments(values,active=''){for(const key of Object.keys(COLOR_DEFAULTS))$('color_'+key).value=values[key]??0;for(const button of document.querySelectorAll('[data-color-style]')){const selected=button.dataset.colorStyle===active;button.classList.toggle('active',selected);button.setAttribute('aria-pressed',String(selected))}outputs()}
function layout(){if(!previewSource)return;const scale=Math.max(.03,Math.min(5,fit?Math.min((wrap.clientWidth-20)/canvas.width,(wrap.clientHeight-20)/canvas.height):zoom));canvas.style.width=canvas.width*scale+'px';canvas.style.height=canvas.height*scale+'px';$('effectZoomLabel').textContent=fit?'Ajustar':Math.round(scale*100)+' %';if(fit)zoom=scale}
function show(){if(globalThis.Event)document.dispatchEvent?.(new Event('lz-work-changed'));if(!previewSource)return;const shown=originalView?previewSource:result||previewSource;canvas.width=shown.width;canvas.height=shown.height;canvas.getContext('2d').drawImage(shown,0,0);canvas.hidden=false;$('effectEmpty').hidden=true;for(const [id,active] of [['effectOriginal',originalView],['effectResult',!originalView]]){$(id).classList.toggle('active',active);$(id).setAttribute('aria-pressed',String(active))}layout()}
function analyze(){$('effectAnalysis').textContent='La transparencia original se conserva. Los ajustes no recortan el diseño.'}
async function upload(file){if(!file||exporting||loading)return;const id=++loadRevision;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>40*1024*1024){status('Usa PNG, JPG o WebP de hasta 40 MB.',true);return}let image;loading=true;sizeInfo();try{status('Cargando imagen…');image=await createImageBitmap(file,{imageOrientation:'from-image'});if(image.width*image.height>32e6)throw Error('La imagen supera 32 MP. Reduce el original antes de cargarlo.');if(id!==loadRevision){image.close();return}source?.close?.();source=image;fileName=file.name;const scale=Math.min(1,1100/Math.max(image.width,image.height));previewSource=document.createElement('canvas');previewSource.width=Math.max(1,Math.round(image.width*scale));previewSource.height=Math.max(1,Math.round(image.height*scale));previewSource.getContext('2d').drawImage(image,0,0,previewSource.width,previewSource.height);result=null;originalView=false;fit=true;$('effectName').textContent=fileName;$('effectSourceSize').textContent=`${image.width.toLocaleString()} × ${image.height.toLocaleString()} px`;$('effectOriginal').disabled=$('effectResult').disabled=false;analyze();sizeInfo();show();render();return true;}catch(error){image?.close?.();status(error.message||'No se pudo abrir la imagen.',true)}finally{loading=false;sizeInfo();$('effectFile').value=''}}
function render(){if(globalThis.Event)document.dispatchEvent?.(new Event('lz-work-changed'));if(!previewSource)return;let p;try{p=params();dimensions(p)}catch(error){status(error.message,true);return}const id=++revision;worker?.terminate();const w=new Worker('worker.js',{type:'module'});worker=w;const pixels=previewSource.getContext('2d',{willReadFrequently:true}).getImageData(0,0,previewSource.width,previewSource.height);$('effectBusy').hidden=false;
  w.onmessage=({data})=>{w.terminate();if(id!==revision)return;worker=null;$('effectBusy').hidden=true;if(data.error){status(data.error,true);return}result=document.createElement('canvas');result.width=previewSource.width;result.height=previewSource.height;result.getContext('2d').putImageData(new ImageData(new Uint8ClampedArray(data.buffer),result.width,result.height),0,0);show();status('Color actualizado. Compara con el original antes de descargar.')};
  w.onerror=()=>{w.terminate();if(id===revision){worker=null;$('effectBusy').hidden=true;status('No se pudo generar la vista previa. Vuelve a cargar la imagen.',true)}};
  w.postMessage({buffer:pixels.data.buffer,width:previewSource.width,height:previewSource.height,params:p,pixelsPerCm:previewSource.width/p.widthCm},[pixels.data.buffer]);
}
function schedule(){outputs();sizeInfo();clearTimeout(timer);timer=setTimeout(render,100)}
$('effectFile').onchange=()=>upload($('effectFile').files[0]);
for(const id of ['effectWidth','effectDpi',...Object.keys(COLOR_DEFAULTS).map(k=>'color_'+k)])$(id).addEventListener('input',()=>{if(id.startsWith('color_'))for(const button of document.querySelectorAll('[data-color-style]')){button.classList.remove('active');button.setAttribute('aria-pressed','false')}schedule()});
$('autoColor').onclick=()=>{if(!previewSource)return;const pixels=previewSource.getContext('2d',{willReadFrequently:true}).getImageData(0,0,previewSource.width,previewSource.height).data;writeAdjustments(autoColorAdjustments(pixels));schedule()};
$('resetColors').onclick=()=>{writeAdjustments(COLOR_DEFAULTS);schedule()};
for(const button of document.querySelectorAll('[data-color-style]'))button.onclick=()=>{writeAdjustments({...COLOR_DEFAULTS,...COLOR_STYLES[button.dataset.colorStyle]},button.dataset.colorStyle);schedule()};
$('effectOriginal').onclick=()=>{originalView=true;show()};$('effectResult').onclick=()=>{originalView=false;show()};
$('effectZoomIn').onclick=()=>{fit=false;zoom=Math.min(5,zoom*1.25);layout()};$('effectZoomOut').onclick=()=>{fit=false;zoom=Math.max(.03,zoom/1.25);layout()};$('effectFit').onclick=()=>{fit=true;wrap.scrollTo(0,0);layout()};wrap.addEventListener('wheel',event=>{if(!source)return;event.preventDefault();fit=false;zoom=Math.max(.03,Math.min(5,zoom*(event.deltaY<0?1.14:1/1.14)));layout()},{passive:false});new ResizeObserver(()=>{if(fit)layout()}).observe(wrap);
$('effectBackground').onchange=()=>{wrap.style.backgroundColor=$('effectBackground').value||'';wrap.classList.toggle('checker',$('effectBackground').value==='')};
function menu(open){$('moduleMenu').hidden=!open;$('menuBackdrop').hidden=!open;$('menuButton').setAttribute('aria-expanded',String(open))}$('menuButton').onclick=()=>menu($('moduleMenu').hidden);$('menuClose').onclick=()=>menu(false);$('menuBackdrop').onclick=()=>menu(false);document.addEventListener('keydown',event=>{if(event.key==='Escape')menu(false)});
$('downloadEffect').onclick=async()=>{if(!source||exporting||loading)return;let p,d;try{p=params();d=dimensions(p)}catch(error){status(error.message,true);return}exporting=true;sizeInfo();$('effectExportDialog').showModal();try{const blob=await exportTiledPng({source,sourceWidth:source.width,sourceHeight:source.height,...d,params:p,onProgress:value=>{$('effectExportProgress').value=Math.round(value*100);$('effectExportText').textContent=`Preparando PNG · ${Math.round(value*100)} %`}}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=fileName.replace(/\.[^.]+$/,'').replace(/[^a-z0-9áéíóúñ _-]/gi,'').slice(0,80)+`_LZ_color_${d.dpi}ppp.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);status(`PNG preparado: ${d.width.toLocaleString()} × ${d.height.toLocaleString()} px · ${d.dpi} ppp.`)}catch(error){status(error.message||'No se pudo exportar.',true)}finally{exporting=false;$('effectExportDialog').close();sizeInfo()}};
$('effectExportDialog').addEventListener('cancel',event=>event.preventDefault());
outputs();sizeInfo();registerStudioModule({id:'color',onFit:()=>{fit=true;layout();},getComparison:()=>[previewSource,result],getDraft:()=>source?{images:{source},data:{fileName}}:null,restoreDraft:async d=>{await upload(new File([d.images.source],d.data.fileName,{type:'image/png'}));},afterRestore:()=>{outputs();sizeInfo();render();},onZoom:factor=>{if(!source)return;fit=false;zoom=Math.max(.03,Math.min(5,zoom*factor));layout();},exportCurrent:async onProgress=>{requireTransferImage(source,exporting||loading);const p=params(),d=dimensions(p);exporting=true;sizeInfo();try{return await processedArtifact({source,...d,params:p,name:fileName.replace(/\.[^.]+$/,'')+'_LZ_resultado.png',onProgress})}finally{exporting=false;sizeInfo()}},importCurrent:async(blob,name)=>upload(new File([blob],name,{type:blob.type}))});
