import {exportBands,outputDimensions,drawBand} from './image-output.js';
import {decodeImageFile,validateImportSize} from './upscale-import.js';
import {registerStudioModule} from './studio-shell.js';
import {contentBounds,clampCrop} from './crop-engine.js';
import {canvasArtifact} from './transfer-export.js';
const $=id=>document.getElementById(id),canvas=$('cropCanvas'),wrap=document.querySelector('.lab-canvas-wrap');
let source=null,rect=null,filename='diseno',zoom=1,fit=true,resultView=false,drag=null,loading=false,scanBusy=false,loadId=0;
const status=(text,error=false)=>{$('cropStatus').textContent=text;$('cropStatus').classList.toggle('error',error);};
function controls(){for(const id of ['autoCrop','resetCrop','viewCropOriginal','viewCropResult','downloadCrop'])$(id).disabled=!source||loading||scanBusy;$('cropFile').disabled=loading||scanBusy;}
function layout(){if(canvas.hidden)return;const scale=fit?Math.min((wrap.clientWidth-24)/canvas.width,(wrap.clientHeight-24)/canvas.height):zoom;zoom=Math.max(.01,Math.min(12,scale));canvas.style.width=canvas.width*zoom+'px';canvas.style.height=canvas.height*zoom+'px';$('cropZoomLabel').textContent=fit?'Ajustar':Math.round(zoom*100)+' %';}
function updateSize(reset=false){if(!rect)return;if(reset)$('cropWidth').value=(rect.width/300*2.54).toFixed(2);const widthCm=Number($('cropWidth').value),dpi=widthCm>0?rect.width/widthCm*2.54:0;$('cropHeight').value=widthCm>0?(widthCm*rect.height/rect.width).toFixed(2):'';$('cropSize').textContent=`${rect.width.toLocaleString()} × ${rect.height.toLocaleString()} px · ${dpi>0?Math.round(dpi):'—'} ppp`;$('cropArea').textContent=`Recorte: ${rect.width} × ${rect.height} px · origen ${rect.x}, ${rect.y}`;}
function show(){if(!source||!rect)return;const width=resultView?rect.width:source.width,height=resultView?rect.height:source.height,scale=Math.min(1,1400/Math.max(width,height));canvas.width=Math.max(1,Math.round(width*scale));canvas.height=Math.max(1,Math.round(height*scale));const ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);if(resultView)ctx.drawImage(source,rect.x,rect.y,rect.width,rect.height,0,0,canvas.width,canvas.height);else{ctx.drawImage(source,0,0,canvas.width,canvas.height);const sx=canvas.width/source.width,sy=canvas.height/source.height;ctx.fillStyle='#0008';ctx.beginPath();ctx.rect(0,0,canvas.width,canvas.height);ctx.rect(rect.x*sx,rect.y*sy,rect.width*sx,rect.height*sy);ctx.fill('evenodd');ctx.strokeStyle='#b8ff3d';ctx.lineWidth=2/Math.max(.1,zoom);ctx.strokeRect(rect.x*sx,rect.y*sy,rect.width*sx,rect.height*sy);const radius=7/Math.max(.1,zoom);for(const [x,y] of [[rect.x,rect.y],[rect.x+rect.width,rect.y],[rect.x,rect.y+rect.height],[rect.x+rect.width,rect.y+rect.height]]){ctx.fillStyle='#b8ff3d';ctx.fillRect(x*sx-radius,y*sy-radius,radius*2,radius*2);}}canvas.hidden=false;$('cropEmpty').hidden=true;for(const [id,on] of [['viewCropOriginal',!resultView],['viewCropResult',resultView]]){$(id).classList.toggle('active',on);$(id).setAttribute('aria-pressed',String(on));}layout();updateSize();document.dispatchEvent(new Event('lz-work-changed'));}
async function upload(file){if(!file)return false;const id=++loadId;loading=true;controls();let image;try{if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>150*1024*1024)throw Error('Usa PNG, JPG o WebP de hasta 150 MB.');status('Cargando imagen…');image=await decodeImageFile(file);validateImportSize(image.width,image.height);if(id!==loadId){image.close?.();return false;}source?.close?.();source=image;filename=file.name;rect={x:0,y:0,width:source.width,height:source.height};resultView=false;fit=true;$('cropName').textContent=filename;$('cropSourceSize').textContent=`Original: ${source.width} × ${source.height} px`;updateSize(true);show();status('Quita los márgenes transparentes o dibuja el recorte sobre el original.');return true;}catch(error){if(image!==source)image?.close?.();status(error.message||'No se pudo abrir la imagen.',true);return false;}finally{loading=false;controls();$('cropFile').value='';}}
$('cropFile').onchange=()=>upload($('cropFile').files[0]);
$('autoCrop').onclick=async()=>{if(!source||scanBusy)return;scanBusy=true;controls();status('Buscando márgenes transparentes…');await new Promise(requestAnimationFrame);try{const c=document.createElement('canvas');let left=source.width,top=source.height,right=-1,bottom=-1;for(let y=0;y<source.height;y+=64){const rows=Math.min(64,source.height-y),data=drawBand(c,source,source.width,source.height,y,rows),b=contentBounds(data.data,source.width,rows);if(b){left=Math.min(left,b.x);right=Math.max(right,b.x+b.width-1);top=Math.min(top,y+b.y);bottom=Math.max(bottom,y+b.y+b.height-1);}await new Promise(requestAnimationFrame);}c.width=c.height=1;const bounds=right<0?null:{x:left,y:top,width:right-left+1,height:bottom-top+1};if(!bounds){status('La imagen está completamente transparente. No hay diseño que recortar.',true);return;}rect=bounds;resultView=true;fit=true;updateSize(true);show();status(bounds.width===source.width&&bounds.height===source.height?'No hay márgenes transparentes. Si el sobrante tiene color, usa el recorte manual.':'Márgenes transparentes recortados. Se conservaron todos los píxeles visibles.');}catch(error){status(error.message||'No se pudo calcular el recorte.',true);}finally{scanBusy=false;controls();}};
function point(event){const box=canvas.getBoundingClientRect();return {x:Math.max(0,Math.min(source.width,(event.clientX-box.left)/box.width*source.width)),y:Math.max(0,Math.min(source.height,(event.clientY-box.top)/box.height*source.height))};}
canvas.addEventListener('pointerdown',event=>{if(!source||loading||scanBusy||resultView||event.button!==0)return;const p=point(event),box=canvas.getBoundingClientRect(),radius=18*source.width/box.width;const corners=[[rect.x,rect.y],[rect.x+rect.width,rect.y],[rect.x,rect.y+rect.height],[rect.x+rect.width,rect.y+rect.height]];let corner=corners.findIndex(([x,y])=>Math.hypot(x-p.x,y-p.y)<=radius);if(corner>=0){const opposite=corners[3-corner];drag={id:event.pointerId,kind:'resize',start:{x:opposite[0],y:opposite[1]}};}else if(p.x>rect.x&&p.x<rect.x+rect.width&&p.y>rect.y&&p.y<rect.y+rect.height&&!(rect.width===source.width&&rect.height===source.height)){drag={id:event.pointerId,kind:'move',start:p,rect:{...rect}};}else drag={id:event.pointerId,kind:'select',start:p};drag.moved=false;canvas.setPointerCapture(event.pointerId);event.preventDefault();});
canvas.addEventListener('pointermove',event=>{if(!drag||drag.id!==event.pointerId)return;const p=point(event);drag.moved=true;if(drag.kind==='move')rect=clampCrop({...drag.rect,x:Math.max(0,Math.min(source.width-drag.rect.width,drag.rect.x+p.x-drag.start.x)),y:Math.max(0,Math.min(source.height-drag.rect.height,drag.rect.y+p.y-drag.start.y))},source.width,source.height);else rect=clampCrop({x:Math.min(drag.start.x,p.x),y:Math.min(drag.start.y,p.y),width:Math.abs(p.x-drag.start.x),height:Math.abs(p.y-drag.start.y)},source.width,source.height);show();event.preventDefault();});
const end=event=>{if(!drag||drag.id!==event.pointerId)return;const moved=drag.moved;drag=null;if(canvas.hasPointerCapture(event.pointerId))canvas.releasePointerCapture(event.pointerId);updateSize(moved);show();};canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);canvas.addEventListener('lostpointercapture',end);
$('resetCrop').onclick=()=>{if(!source)return;rect={x:0,y:0,width:source.width,height:source.height};resultView=false;fit=true;updateSize(true);show();};$('viewCropOriginal').onclick=()=>{resultView=false;fit=true;show();};$('viewCropResult').onclick=()=>{resultView=true;fit=true;show();};$('cropWidth').oninput=()=>updateSize();
function zoomBy(factor){if(!source)return;fit=false;zoom=Math.max(.01,Math.min(12,zoom*factor));layout();}function fitView(){fit=true;wrap.scrollTo(0,0);layout();}
$('cropZoomIn').onclick=()=>zoomBy(1.25);$('cropZoomOut').onclick=()=>zoomBy(.8);$('cropFit').onclick=fitView;new ResizeObserver(()=>{if(fit)layout();}).observe(wrap);
async function artifact(){if(!source||!rect)throw Error('Carga una imagen y elige el recorte.');const widthCm=Number($('cropWidth').value);if(!Number.isFinite(widthCm)||widthCm<=0||widthCm>100)throw Error('Indica un ancho de más de 0 y hasta 100 cm.');return {blob:await exportBands({source,width:rect.width,height:rect.height,dpi:rect.width/widthCm*2.54,rect}),width:rect.width,height:rect.height,widthCm,dpi:rect.width/widthCm*2.54,name:filename.replace(/\.[^.]+$/,'')+'_LZ_recortado.png'};}
$('downloadCrop').onclick=async()=>{try{$('downloadCrop').disabled=true;const data=await artifact(),url=URL.createObjectURL(data.blob),a=document.createElement('a');a.href=url;a.download=data.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);status('PNG recortado descargado. No se amplió ni redujo la imagen.');}catch(error){status(error.message,true);}finally{controls();}};
const menu=open=>{$('moduleMenu').hidden=!open;$('menuBackdrop').hidden=!open;$('menuButton').setAttribute('aria-expanded',String(open));};$('menuButton').onclick=()=>menu($('moduleMenu').hidden);$('menuClose').onclick=()=>menu(false);$('menuBackdrop').onclick=()=>menu(false);document.addEventListener('keydown',e=>{if(e.key==='Escape')menu(false);});
controls();registerStudioModule({id:'crop',onZoom:zoomBy,onFit:fitView,getExportInfo:()=>rect?{widthCm:Number($('cropWidth').value),dpi:rect.width/Number($('cropWidth').value)*2.54,aspect:rect.width/rect.height}:null,exportAtSize:async(size,onProgress)=>{if(!source||loading||scanBusy)throw Error('Espera a que termine el recorte.');const d=outputDimensions(size.widthCm,size.dpi,rect.width/rect.height);return {...d,blob:await exportBands({source,...d,rect,onProgress}),name:filename.replace(/\.[^.]+$/,'')+'_LZ_recortado.png'};},exportCurrent:artifact,importCurrent:async(blob,name)=>upload(new File([blob],name,{type:blob.type})),getDraft:()=>source?{images:{source},data:{rect,filename}}:null,restoreDraft:async d=>{if(!await upload(new File([d.images.source],d.data.filename,{type:'image/png'})))throw Error('No se pudo recuperar la imagen.');rect=clampCrop(d.data.rect,source.width,source.height);},afterRestore:()=>{resultView=false;show();}});
