import {originalImageBlob} from './upscale-import.js';
import {exportBands} from './image-output.js';
const DB='lz-workspaces',STORE='drafts';
function open(){return new Promise((resolve,reject)=>{if(!globalThis.indexedDB)return reject(Error('El navegador no permite guardar el trabajo.'));const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:'key'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.onblocked=()=>reject(Error('Cierra otras pestañas e intenta guardar de nuevo.'));});}
export async function draftOperation(key,value){const db=await open();try{return await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,value===undefined?'readonly':'readwrite'),store=tx.objectStore(STORE);let output;const req=value===undefined?store.get(key):value===null?store.delete(key):store.put({...value,key,updatedAt:Date.now()});req.onsuccess=()=>{output=req.result};tx.oncomplete=()=>resolve(output);tx.onerror=tx.onabort=()=>reject(tx.error||Error('No se pudo guardar el trabajo.'));});}finally{db.close();}}
export function collectSettings(root=document){const values={};for(const field of root.querySelectorAll('input[id],select[id],textarea[id]')){if(field.closest('.lz-workspace-options,dialog')||['file','password','hidden'].includes(field.type)||field.readOnly||field.id.startsWith('lz-'))continue;values[field.id]=field.type==='checkbox'?field.checked:field.value;}return values;}
export function applySettings(values,root=document,emit=true){for(const [id,value] of Object.entries(values||{})){const field=root.getElementById?root.getElementById(id):root.querySelector('#'+CSS.escape(id));if(!field||field.type==='file'||field.type==='password'||field.readOnly)continue;if(field.type==='checkbox')field.checked=Boolean(value);else field.value=String(value);if(emit){field.dispatchEvent(new Event('input',{bubbles:true}));field.dispatchEvent(new Event('change',{bubbles:true}));}}}
const imageCache=new WeakMap();
export async function imageBlob(image){if(image instanceof Blob)return image;if(!image)return null;if(originalImageBlob(image))return originalImageBlob(image);if(image.constructor?.name==='ImageBitmap'&&imageCache.has(image))return imageCache.get(image);if(!image.data&&(image.width||image.naturalWidth)*(image.height||image.naturalHeight)>16e6){const blob=await exportBands({source:image,width:image.width||image.naturalWidth,height:image.height||image.naturalHeight,dpi:300});imageCache.set(image,blob);return blob;}const c=document.createElement('canvas');c.width=image.width||image.naturalWidth;c.height=image.height||image.naturalHeight;if(!c.width||!c.height)throw Error('No hay imagen para guardar.');if(image.data)c.getContext('2d').putImageData(image,0,0);else c.getContext('2d').drawImage(image,0,0,c.width,c.height);const blob=await new Promise((resolve,reject)=>c.toBlob(v=>v?resolve(v):reject(Error('No se pudo guardar la imagen.')),'image/png'));if(image.constructor?.name==='ImageBitmap')imageCache.set(image,blob);c.width=c.height=1;return blob;}
export async function serializeDraft(raw){if(!raw)return null;const images={};let bytes=0;for(const [id,image] of Object.entries(raw.images||{})){if(!image)continue;const blob=await imageBlob(image);bytes+=blob.size;if(bytes>350*1024*1024)throw Error('Este trabajo es demasiado grande para el borrador. Descárgalo para conservarlo.');images[id]=blob;}return {...raw,images};}
