import {canvasArtifact,processedArtifact,requireTransferImage} from './transfer-export.js';
import {registerStudioModule} from './studio-shell.js';
import {exportTiledPng} from './exporter.js';
import {createOpacityAudit} from './opacity-audit-ui.js';
import {minimumDetailPixels} from './dtf-audit-engine.js';
const $=id=>document.getElementById(id),tool=document.body.dataset.effectTool;
let source=null,previewSource=null,result=null,fileName='diseno',zoom=1,fit=true,originalView=false,worker=null,revision=0,loadRevision=0,timer,exporting=false,seed=17;
const canvas=$('effectCanvas'),wrap=document.querySelector('.lab-canvas-wrap');
let audit=null;
function status(message,error=false){$('effectStatus').textContent=message;$('effectStatus').classList.toggle('error',error)}
function params(){if(tool==='opacity'&&$('effectReinforce').checked)minimumDetailPixels(Number($('auditMinimum').value),1);return {effectTool:tool,widthCm:Number($('effectWidth').value),textureType:$('textureType')?.value||'worn',effectAmount:Number($('effectAmount')?.value||0),effectSizeMm:Number($('effectSize').value),effectAngle:Number($('effectAngle')?.value||45),effectSeed:seed,effectSolidAlpha:$('effectSolidAlpha')?.checked??true,alphaMethod:$('alphaMethod')?.value||'screen',alphaThreshold:Number($('alphaThreshold')?.value||50),effectMinDetailMm:tool==='opacity'&&$('effectReinforce').checked?Number($('auditMinimum').value):0}}
function dimensions(p=params()){const dpi=Number($('effectDpi').value),width=Math.round(p.widthCm/2.54*dpi),height=source?Math.round(width*source.height/source.width):0;if(!Number.isFinite(p.widthCm)||p.widthCm<.5||p.widthCm>100)throw Error('Indica un ancho entre 0.5 y 100 cm.');if(width*height>140e6||Math.max(width,height)>24000)throw Error('Reduce la medida o la resolución: máximo 140 MP y 24,000 px por lado.');return {width,height,dpi}}
function sizeInfo(){$('effectFile').disabled=exporting;try{const d=dimensions();$('effectHeight').value=source?(params().widthCm*source.height/source.width).toFixed(2):'';$('effectPixels').textContent=source?`${d.width.toLocaleString()} × ${d.height.toLocaleString()} px · ${d.dpi} ppp`:'';$('downloadEffect').disabled=!source||exporting}catch(error){$('downloadEffect').disabled=true;status(error.message,true)}}
function outputs(){for(const id of ['effectAmount','effectAngle','alphaThreshold'])if($(id))$(id+'Out').value=$(id).value+(id==='effectAngle'?'°':' %');if(tool==='opacity'){$('alphaScreenControls').hidden=$('alphaMethod').value!=='screen';$('alphaThresholdControls').hidden=$('alphaMethod').value!=='threshold'}}
function layout(){if(!previewSource)return;const scale=Math.max(.03,Math.min(5,fit?Math.min((wrap.clientWidth-20)/canvas.width,(wrap.clientHeight-20)/canvas.height):zoom));canvas.style.width=canvas.width*scale+'px';canvas.style.height=canvas.height*scale+'px';$('effectZoomLabel').textContent=fit?'Ajustar':Math.round(scale*100)+' %';if(fit)zoom=scale}
function show(){if(globalThis.Event)document.dispatchEvent?.(new Event('lz-work-changed'));if(!previewSource)return;const target=originalView?'original':'result',shown=audit?.previewFor(target)||(originalView?previewSource:result||previewSource);canvas.width=shown.width;canvas.height=shown.height;const ctx=canvas.getContext('2d');ctx.drawImage(shown,0,0);canvas.hidden=false;$('effectEmpty').hidden=true;for(const [id,active] of [['effectOriginal',originalView],['effectResult',!originalView]]){$(id).classList.toggle('active',active);$(id).setAttribute('aria-pressed',String(active))}layout();audit?.draw(ctx,canvas,target)}
function analyze(){const d=previewSource.getContext('2d',{willReadFrequently:true}).getImageData(0,0,previewSource.width,previewSource.height).data;let semi=0,visible=0;for(let i=3;i<d.length;i+=4){if(d[i]>0)visible++;if(d[i]>0&&d[i]<255)semi++}$('effectAnalysis').textContent=tool==='opacity'?`${visible?(semi/visible*100).toFixed(1):0} % de los píxeles visibles de la vista previa tienen semitransparencia.`:'La textura recorta transparencia dentro de tu diseño; conserva sus colores.'}
async function upload(file){if(!file||exporting)return;const id=++loadRevision;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>40*1024*1024){status('Usa PNG, JPG o WebP de hasta 40 MB.',true);return}let image;try{status('Cargando imagen…');image=await createImageBitmap(file,{imageOrientation:'from-image'});if(image.width*image.height>32e6)throw Error('La imagen supera 32 MP. Reduce el original antes de cargarlo.');if(id!==loadRevision){image.close();return}source?.close?.();source=image;audit?.invalidate();fileName=file.name;const scale=Math.min(1,1100/Math.max(image.width,image.height));previewSource=document.createElement('canvas');previewSource.width=Math.max(1,Math.round(image.width*scale));previewSource.height=Math.max(1,Math.round(image.height*scale));previewSource.getContext('2d').drawImage(image,0,0,previewSource.width,previewSource.height);result=null;originalView=false;fit=true;$('effectName').textContent=fileName;$('effectSourceSize').textContent=`${image.width.toLocaleString()} × ${image.height.toLocaleString()} px`;$('effectOriginal').disabled=$('effectResult').disabled=false;analyze();sizeInfo();show();render();return true;}catch(error){image?.close?.();status(error.message||'No se pudo abrir la imagen.',true)}finally{$('effectFile').value=''}}
function render(){if(globalThis.Event)document.dispatchEvent?.(new Event('lz-work-changed'));if(!previewSource)return;let p;try{p=params();dimensions(p)}catch(error){status(error.message,true);return}const id=++revision;worker?.terminate();const w=new Worker('worker.js',{type:'module'});worker=w;const pixels=previewSource.getContext('2d',{willReadFrequently:true}).getImageData(0,0,previewSource.width,previewSource.height);$('effectBusy').hidden=false;
  w.onmessage=({data})=>{w.terminate();if(id!==revision)return;worker=null;$('effectBusy').hidden=true;if(data.error){status(data.error,true);return}result=document.createElement('canvas');result.width=previewSource.width;result.height=previewSource.height;result.getContext('2d').putImageData(new ImageData(new Uint8ClampedArray(data.buffer),result.width,result.height),0,0);show();status(tool==='opacity'?'Resultado listo: alfa sólido o transparente. Compara con el original.':'Textura aplicada. Ajusta el desgaste y revisa el resultado.')};
  w.onerror=()=>{w.terminate();if(id===revision){worker=null;$('effectBusy').hidden=true;status('No se pudo generar la vista previa. Vuelve a cargar la imagen.',true)}};
  w.postMessage({buffer:pixels.data.buffer,width:previewSource.width,height:previewSource.height,params:p,pixelsPerCm:previewSource.width/p.widthCm},[pixels.data.buffer]);
}
function schedule(event){if(tool==='opacity'&&event?.target?.id==='effectReinforce'){originalView=false;$('opacityAuditTarget').value='result'}audit?.invalidate();outputs();sizeInfo();show();clearTimeout(timer);timer=setTimeout(render,100)}
$('effectFile').onchange=()=>upload($('effectFile').files[0]);
for(const id of ['effectWidth','effectDpi','textureType','effectAmount','effectSize','effectAngle','effectSolidAlpha','alphaMethod','alphaThreshold','effectReinforce','auditMinimum'])if($(id))$(id).addEventListener('input',schedule);
if($('changeTexture'))$('changeTexture').onclick=()=>{seed++;render()};
$('effectOriginal').onclick=()=>{originalView=true;show()};$('effectResult').onclick=()=>{originalView=false;show()};
$('effectZoomIn').onclick=()=>{fit=false;zoom=Math.min(5,zoom*1.25);layout()};$('effectZoomOut').onclick=()=>{fit=false;zoom=Math.max(.03,zoom/1.25);layout()};$('effectFit').onclick=()=>{fit=true;wrap.scrollTo(0,0);layout()};wrap.addEventListener('wheel',event=>{if(!source)return;event.preventDefault();fit=false;zoom=Math.max(.03,Math.min(5,zoom*(event.deltaY<0?1.14:1/1.14)));layout()},{passive:false});new ResizeObserver(()=>{if(fit)layout()}).observe(wrap);
$('effectBackground').onchange=()=>{wrap.style.backgroundColor=$('effectBackground').value||'';wrap.classList.toggle('checker',$('effectBackground').value==='')};
function menu(open){$('moduleMenu').hidden=!open;$('menuBackdrop').hidden=!open;$('menuButton').setAttribute('aria-expanded',String(open))}$('menuButton').onclick=()=>menu($('moduleMenu').hidden);$('menuClose').onclick=()=>menu(false);$('menuBackdrop').onclick=()=>menu(false);document.addEventListener('keydown',event=>{if(event.key==='Escape')menu(false)});
$('downloadEffect').onclick=async()=>{if(!source||exporting)return;let p,d;try{p=params();d=dimensions(p)}catch(error){status(error.message,true);return}exporting=true;sizeInfo();$('effectExportDialog').showModal();try{const blob=await exportTiledPng({source,sourceWidth:source.width,sourceHeight:source.height,...d,params:p,onProgress:value=>{$('effectExportProgress').value=Math.round(value*100);$('effectExportText').textContent=`Preparando PNG · ${Math.round(value*100)} %`}}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=fileName.replace(/\.[^.]+$/,'').replace(/[^a-z0-9áéíóúñ _-]/gi,'').slice(0,80)+`_LZ_${tool==='opacity'?'alfa':'textura'}_${d.dpi}ppp.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);status(`PNG preparado: ${d.width.toLocaleString()} × ${d.height.toLocaleString()} px · ${d.dpi} ppp.`)}catch(error){status(error.message||'No se pudo exportar.',true)}finally{exporting=false;$('effectExportDialog').close();sizeInfo()}};
$('effectExportDialog').addEventListener('cancel',event=>event.preventDefault());
if(tool==='opacity')audit=createOpacityAudit({getSource:()=>source,getParams:params,getDimensions:dimensions,selectTarget:target=>{originalView=target==='original';show();if(window.matchMedia?.('(max-width:700px)')?.matches)document.querySelector('.lz-mobile-switch [data-pane="view"]')?.click()},redraw:show});
outputs();sizeInfo();registerStudioModule({id:tool==='opacity'?'opacity':'texture',onFit:()=>{fit=true;layout();},getComparison:()=>[previewSource,result],getDraft:()=>source?{images:{source},data:{fileName,seed}}:null,restoreDraft:async d=>{await upload(new File([d.images.source],d.data.fileName,{type:'image/png'}));seed=d.data.seed;},afterRestore:()=>{outputs();sizeInfo();render();},onZoom:factor=>{if(!source)return;fit=false;zoom=Math.max(.03,Math.min(5,zoom*factor));layout();},exportCurrent:async onProgress=>{requireTransferImage(source,exporting);const p=params(),d=dimensions(p);exporting=true;sizeInfo();try{return await processedArtifact({source,...d,params:p,name:fileName.replace(/\.[^.]+$/,'')+'_LZ_resultado.png',onProgress})}finally{exporting=false;sizeInfo()}},importCurrent:async(blob,name)=>upload(new File([blob],name,{type:blob.type}))});
