import {crc32} from './png.js';
import {clarityRadius} from './color-engine.js';
import {detailMargin} from './dtf-audit-engine.js';

const encoder=new TextEncoder();
function be32(value){const out=new Uint8Array(4);new DataView(out.buffer).setUint32(0,value);return out;}
function chunk(type,data){const name=encoder.encode(type),out=new Uint8Array(12+data.length);out.set(be32(data.length),0);out.set(name,4);out.set(data,8);out.set(be32(crc32(out.subarray(4,8+data.length))),8+data.length);return out;}
function header(width,height,dpi){const ihdr=new Uint8Array(13),view=new DataView(ihdr.buffer);view.setUint32(0,width);view.setUint32(4,height);ihdr.set([8,6,0,0,0],8);const phys=new Uint8Array(9),pv=new DataView(phys.buffer),ppm=Math.round(dpi/.0254);pv.setUint32(0,ppm);pv.setUint32(4,ppm);phys[8]=1;return [Uint8Array.from([137,80,78,71,13,10,26,10]),chunk('IHDR',ihdr),chunk('pHYs',phys)];}
export function assemblePng(width,height,dpi,compressed){const parts=header(width,height,dpi),block=8*1024*1024;for(let i=0;i<compressed.length;i+=block)parts.push(chunk('IDAT',compressed.subarray(i,Math.min(compressed.length,i+block))));parts.push(chunk('IEND',new Uint8Array()));return new Blob(parts,{type:'image/png'});}
function processTile(worker,pixels,width,height,params,pixelsPerCm,offsetX,offsetY){return new Promise((resolve,reject)=>{const onMessage=({data})=>{worker.removeEventListener('message',onMessage);worker.removeEventListener('error',onError);if(data.error)reject(Error(data.error));else resolve(new Uint8ClampedArray(data.buffer));},onError=()=>{worker.removeEventListener('message',onMessage);worker.removeEventListener('error',onError);reject(Error('No se pudo procesar un bloque de la imagen.'));};worker.addEventListener('message',onMessage);worker.addEventListener('error',onError);worker.postMessage({buffer:pixels.buffer,width,height,params,pixelsPerCm,offsetX,offsetY},[pixels.buffer]);});}
export async function exportTiledPng({source,sourceWidth,sourceHeight,width,height,dpi,params,onProgress}){
 if(typeof CompressionStream==='undefined')throw Error('Este navegador no permite exportar archivos grandes. Actualízalo o abre la página en Chrome, Edge o Safari reciente.');
 const compressor=new CompressionStream('deflate'),writer=compressor.writable.getWriter(),compressedPromise=new Response(compressor.readable).arrayBuffer();
 const worker=new Worker('worker.js',{type:'module'}),tile=document.createElement('canvas'),maxTileWidth=2048,rowsPerTile=params.cleanupOn?256:64,pixelsPerCm=width/params.widthCm,margin=params.effectTool==='opacity'&&params.effectMinDetailMm?detailMargin(Number(params.effectMinDetailMm),pixelsPerCm):params.effectTool==='color'&&params.colorAdjustments?.clarity?clarityRadius(pixelsPerCm):params.cleanupOn?Math.min(32,Math.max(2,Math.ceil(pixelsPerCm*(params.cleanupSize||.3)/10)+2)):0;
 try{for(let y=0;y<height;y+=rowsPerTile){const rows=Math.min(rowsPerTile,height-y),stride=width*4,scanlines=new Uint8Array(rows*(stride+1));for(let x=0;x<width;x+=maxTileWidth){const cols=Math.min(maxTileWidth,width-x),left=Math.max(0,x-margin),top=Math.max(0,y-margin),right=Math.min(width,x+cols+margin),bottom=Math.min(height,y+rows+margin),tileW=right-left,tileH=bottom-top;tile.width=tileW;tile.height=tileH;const ctx=tile.getContext('2d',{willReadFrequently:true,alpha:true}),sx=left/width*sourceWidth,sw=tileW/width*sourceWidth,sy=top/height*sourceHeight,sh=tileH/height*sourceHeight;ctx.drawImage(source,sx,sy,sw,sh,0,0,tileW,tileH);const image=ctx.getImageData(0,0,tileW,tileH),processed=await processTile(worker,image.data,tileW,tileH,params,pixelsPerCm,left,top),cropX=x-left,cropY=y-top;for(let row=0;row<rows;row++){const start=((row+cropY)*tileW+cropX)*4;scanlines.set(processed.subarray(start,start+cols*4),row*(stride+1)+1+x*4);}}await writer.write(scanlines);onProgress?.(Math.min(1,(y+rows)/height));await new Promise(requestAnimationFrame);}await writer.close();}catch(error){await writer.abort(error).catch(()=>{});throw error;}finally{worker.terminate();tile.width=1;tile.height=1;}
 return assemblePng(width,height,dpi,new Uint8Array(await compressedPromise));
}
