import {decodeImageFile,validateImportSize} from './upscale-import.js';
import {canvasArtifact,processedArtifact,requireTransferImage} from './transfer-export.js';
import {assemblePng} from './exporter.js';
import {registerStudioModule} from './studio-shell.js';
import {CORNERS,cornerPosition,resizeFromCorner} from './sheet-transform.js';
const $=id=>document.getElementById(id),PREVIEW_PPCM=10,SHEET_WIDTH_CM=58;let items=[],selected=null,drag=null,zoom=Math.max(.48,Math.min(1,(innerWidth-44)/(SHEET_WIDTH_CM*PREVIEW_PPCM))),sheetFit=true,exporting=false,nextId=1,lastSizeField='width';
const canvas=$('sheetCanvas'),ctx=canvas.getContext('2d');
let sheetArtwork=null;
function drawArtwork(target,ppcm,offsetY=0,list=items){for(const item of list){target.save();target.translate(item.x*ppcm,item.y*ppcm-offsetY);target.rotate(item.rotation*Math.PI/180);target.drawImage(item.image,-item.widthCm*ppcm/2,-item.heightCm*ppcm/2,item.widthCm*ppcm,item.heightCm*ppcm);target.restore();}}
function status(message,error=false){$('sheetStatus').textContent=message;$('sheetStatus').classList.toggle('error',error)}
function menu(open){$('moduleMenu').hidden=!open;$('menuBackdrop').hidden=!open;$('menuButton').setAttribute('aria-expanded',String(open))}$('menuButton').onclick=()=>menu($('moduleMenu').hidden);$('menuClose').onclick=()=>menu(false);$('menuBackdrop').onclick=()=>menu(false);document.addEventListener('keydown',e=>{if(e.key==='Escape')menu(false);if((e.key==='Delete'||e.key==='Backspace')&&selected&&!['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName))removeSelected()});
function lengthCm(){return Math.max(50,Math.min(500,Number($('sheetLength').value)||100))}
function dimensions(){const dpi=Number($('sheetDpi').value),w=Math.round(SHEET_WIDTH_CM/2.54*dpi),h=Math.round(lengthCm()/2.54*dpi);return {dpi,w,h,mp:w*h/1e6}}
function updateDimensions(){const length=lengthCm();$('sheetLength').value=length;canvas.width=SHEET_WIDTH_CM*PREVIEW_PPCM;canvas.height=length*PREVIEW_PPCM;const d=dimensions();$('sheetPixels').textContent=`${d.w.toLocaleString()} × ${d.h.toLocaleString()} px · ${d.mp.toFixed(1)} MP`;$('sheetSummary').textContent=`58 × ${length} cm · ${items.length} diseño${items.length===1?'':'s'}`;render()}
function fitSheet(){const wrap=document.querySelector('.pliego-wrap');zoom=Math.max(.25,Math.min(3,(wrap.clientWidth-20)/canvas.width));sheetFit=true;render()}
function rotatedBounds(item){const w=item.widthCm,h=item.heightCm,a=item.rotation*Math.PI/180;return {w:Math.abs(w*Math.cos(a))+Math.abs(h*Math.sin(a)),h:Math.abs(w*Math.sin(a))+Math.abs(h*Math.cos(a))}}
function clamp(item){const b=rotatedBounds(item),length=lengthCm();item.x=Math.max(b.w/2,Math.min(SHEET_WIDTH_CM-b.w/2,item.x));item.y=Math.max(b.h/2,Math.min(length-b.h/2,item.y))}
function render(){
 if(globalThis.Event)document.dispatchEvent?.(new Event('lz-work-changed'));
 ctx.clearRect(0,0,canvas.width,canvas.height);ctx.save();ctx.strokeStyle='#343a3e';ctx.lineWidth=1;
 for(let x=0;x<=SHEET_WIDTH_CM;x+=5){ctx.beginPath();ctx.moveTo(x*PREVIEW_PPCM,0);ctx.lineTo(x*PREVIEW_PPCM,canvas.height);ctx.stroke()}
 for(let y=0;y<=lengthCm();y+=5){ctx.beginPath();ctx.moveTo(0,y*PREVIEW_PPCM);ctx.lineTo(canvas.width,y*PREVIEW_PPCM);ctx.stroke()}ctx.restore();
 // Correct the composed artwork, as in export, without processing guides/handles.
 if(['sheetVibrance','cmykSafe','sheetSolidAlpha'].some(id=>$(id).checked)){
  sheetArtwork??=document.createElement('canvas');sheetArtwork.width=canvas.width;sheetArtwork.height=canvas.height;
  const art=sheetArtwork.getContext('2d',{willReadFrequently:true});drawArtwork(art,PREVIEW_PPCM);
  const image=art.getImageData(0,0,sheetArtwork.width,sheetArtwork.height);processBand(image.data);art.putImageData(image,0,0);ctx.drawImage(sheetArtwork,0,0);
 }else{if(sheetArtwork){sheetArtwork.width=sheetArtwork.height=1;sheetArtwork=null;}drawArtwork(ctx,PREVIEW_PPCM);}
 if(selected){ctx.save();ctx.translate(selected.x*PREVIEW_PPCM,selected.y*PREVIEW_PPCM);ctx.rotate(selected.rotation*Math.PI/180);const w=selected.widthCm*PREVIEW_PPCM,h=selected.heightCm*PREVIEW_PPCM;
  ctx.strokeStyle='#b8ff3d';ctx.lineWidth=2/zoom;ctx.setLineDash([8/zoom,5/zoom]);ctx.strokeRect(-w/2,-h/2,w,h);ctx.setLineDash([]);const handle=12/zoom;ctx.fillStyle='#090b0c';
  for(const [sx,sy] of CORNERS){ctx.fillRect(sx*w/2-handle/2,sy*h/2-handle/2,handle,handle);ctx.strokeRect(sx*w/2-handle/2,sy*h/2-handle/2,handle,handle)}ctx.restore();
 }
 $('sheetStage').style.width=canvas.width*zoom+'px';$('sheetStage').style.height=canvas.height*zoom+'px';canvas.style.width=canvas.width*zoom+'px';canvas.style.height=canvas.height*zoom+'px';$('sheetZoomLabel').textContent=Math.round(zoom*100)+' %';
 const badge=$('sheetSizeBadge');badge.hidden=!selected;if(selected){badge.textContent=`${selected.widthCm.toFixed(1)} × ${selected.heightCm.toFixed(1)} cm`;badge.style.left=Math.max(70,Math.min(canvas.width*zoom-70,selected.x*PREVIEW_PPCM*zoom))+'px';badge.style.top=Math.max(18,Math.min(canvas.height*zoom-18,(selected.y+rotatedBounds(selected).h/2)*PREVIEW_PPCM*zoom-18))+'px';}
 $('downloadSheet').disabled=!items.length||exporting;$('autoArrange').disabled=!items.length;$('sheetSummary').textContent=`58 × ${lengthCm()} cm · ${items.length} diseño${items.length===1?'':'s'}`;
}
function hitTest(x,y){for(let i=items.length-1;i>=0;i--){const item=items[i],dx=x-item.x,dy=y-item.y,a=-item.rotation*Math.PI/180,rx=dx*Math.cos(a)-dy*Math.sin(a),ry=dx*Math.sin(a)+dy*Math.cos(a);if(Math.abs(rx)<=item.widthCm/2&&Math.abs(ry)<=item.heightCm/2)return item}return null}
function pointer(event){const r=canvas.getBoundingClientRect();return {x:(event.clientX-r.left)/r.width*SHEET_WIDTH_CM,y:(event.clientY-r.top)/r.height*lengthCm()}}
function resizeHit(p,event){
  if(!selected)return null;
  const radius=(event.pointerType==='touch'?18:10)/(zoom*PREVIEW_PPCM);
  return CORNERS.find(corner=>{const q=cornerPosition(selected,corner);return Math.hypot(p.x-q.x,p.y-q.y)<=radius})||null;
}
canvas.addEventListener('pointerdown',event=>{
  if(event.button!==0||event.isPrimary===false||drag)return;
  const p=pointer(event),corner=resizeHit(p,event);
  if(corner){drag={id:event.pointerId,kind:'resize',corner,start:{...selected},lockRatio:$('lockRatio').checked};canvas.classList.add('resizing')}
  else{
    const hit=hitTest(p.x,p.y);select(hit);if(!hit)return;
    items=items.filter(item=>item!==hit);items.push(hit);
    drag={id:event.pointerId,kind:'move',dx:p.x-hit.x,dy:p.y-hit.y};canvas.classList.add('dragging');
  }
  canvas.setPointerCapture(event.pointerId);event.preventDefault();render();
});
canvas.addEventListener('pointermove',event=>{
  const p=pointer(event);
  if(!drag){canvas.style.cursor=resizeHit(p,event)?'nwse-resize':hitTest(p.x,p.y)?'move':'grab';return}
  if(drag.id!==event.pointerId||!selected)return;
  if(drag.kind==='resize')Object.assign(selected,resizeFromCorner(drag.start,drag.corner,p,drag.lockRatio,SHEET_WIDTH_CM,lengthCm()));
  else{selected.x=p.x-drag.dx;selected.y=p.y-drag.dy;clamp(selected)}
  syncControls();render();
});
function stop(event){
  if(!drag||drag.id!==event.pointerId)return;
  const resized=drag.kind==='resize';drag=null;canvas.classList.remove('dragging','resizing');canvas.style.cursor='';
  if(canvas.hasPointerCapture(event.pointerId))canvas.releasePointerCapture(event.pointerId);
  renderList();if(resized&&selected)status(`Tamaño del diseño: ${selected.widthCm.toFixed(1)} × ${selected.heightCm.toFixed(1)} cm.`);
}
canvas.addEventListener('pointerup',stop);canvas.addEventListener('pointercancel',stop);canvas.addEventListener('lostpointercapture',stop);

function select(item){selected=item;$('itemControls').hidden=!item;$('editSelectedMobile').disabled=!item;if(item)syncControls();renderList();render()}
function syncControls(){if(!selected)return;$('itemWidth').value=selected.widthCm.toFixed(1);$('itemHeight').value=selected.heightCm.toFixed(1);$('itemX').value=selected.x.toFixed(1);$('itemY').value=selected.y.toFixed(1);$('itemRotation').value=selected.rotation;$('itemRotationOut').value=selected.rotation+'°';$('editSelectedMobile').disabled=false}
function renderList(){$('imageList').innerHTML=items.map(item=>`<button class="image-item${item===selected?' active':''}" data-id="${item.id}"><img src="${item.url}" alt=""><span>${item.name}</span><small>${item.widthCm.toFixed(1)} × ${item.heightCm.toFixed(1)} cm</small></button>`).join('');for(const button of document.querySelectorAll('.image-item'))button.onclick=()=>select(items.find(item=>item.id===Number(button.dataset.id)))}
async function addFiles(files){for(const file of files){if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>150*1024*1024){status(`${file.name}: formato o peso no compatible.`,true);continue}try{const image=await decodeImageFile(file);validateImportSize(image.width,image.height);const widthCm=Math.min(15,SHEET_WIDTH_CM-1),heightCm=widthCm*image.height/image.width,item={id:nextId++,name:file.name,image,url:URL.createObjectURL(file),aspectRatio:image.width/image.height,widthCm,heightCm,x:SHEET_WIDTH_CM/2,y:Math.min(lengthCm()-heightCm/2,2+heightCm/2+items.length),rotation:0};clamp(item);items.push(item);selected=item}catch{status(`No se pudo abrir ${file.name}.`,true)}}renderList();syncControls();$('itemControls').hidden=!selected;render();status(`${files.length} archivo${files.length===1?'':'s'} agregado${files.length===1?'':'s'} al pliego. Selecciona uno y arrastra sus esquinas para cambiar el tamaño.`)}
$('sheetFiles').onchange=()=>{addFiles([...$('sheetFiles').files]);$('sheetFiles').value=''};
function applyMeasurements(){if(!selected)return;let width=Math.max(.5,Math.min(57,Number($('itemWidth').value)||selected.widthCm)),height=Math.max(.5,Math.min(lengthCm()-.5,Number($('itemHeight').value)||selected.heightCm));if($('lockRatio').checked){if(lastSizeField==='height')width=height*selected.aspectRatio;else height=width/selected.aspectRatio;if(width>57){width=57;height=width/selected.aspectRatio}if(height>lengthCm()-.5){height=lengthCm()-.5;width=height*selected.aspectRatio}}selected.widthCm=width;selected.heightCm=height;selected.x=Number.isFinite(Number($('itemX').value))?Number($('itemX').value):selected.x;selected.y=Number.isFinite(Number($('itemY').value))?Number($('itemY').value):selected.y;selected.rotation=Number($('itemRotation').value);clamp(selected);syncControls();renderList();render();status(`Medidas aplicadas: ${selected.widthCm.toFixed(1)} × ${selected.heightCm.toFixed(1)} cm.`)}
$('itemWidth').addEventListener('input',()=>{lastSizeField='width'});$('itemHeight').addEventListener('input',()=>{lastSizeField='height'});for(const id of ['itemWidth','itemHeight','itemX','itemY'])$(id).addEventListener('change',applyMeasurements);$('itemRotation').addEventListener('input',()=>{if(!selected)return;selected.rotation=Number($('itemRotation').value);$('itemRotationOut').value=selected.rotation+'°';clamp(selected);render()});$('applyItemSize').onclick=applyMeasurements;
function removeSelected(){if(!selected)return;const old=selected;items=items.filter(item=>item!==old);if(!items.some(item=>item.url===old.url))URL.revokeObjectURL(old.url);selected=items.at(-1)||null;$('itemControls').hidden=!selected;$('editSelectedMobile').disabled=!selected;if(selected)syncControls();renderList();render();status('Diseño eliminado del pliego.')}
$('deleteItem').onclick=removeSelected;$('duplicateItem').onclick=()=>{if(!selected)return;const copy={...selected,id:nextId++,name:selected.name+' copia',url:selected.url,x:selected.x+1,y:selected.y+1};clamp(copy);items.push(copy);select(copy);status('Diseño duplicado.')};$('editSelectedMobile').onclick=()=>{$('itemControls').scrollIntoView({behavior:'smooth',block:'start'})};
$('autoArrange').onclick=()=>{let x=.5,y=.5,rowH=0;for(const item of items){if(x+item.widthCm>SHEET_WIDTH_CM-.5){x=.5;y+=rowH+.5;rowH=0}item.rotation=0;item.x=x+item.widthCm/2;item.y=y+item.heightCm/2;x+=item.widthCm+.5;rowH=Math.max(rowH,item.heightCm)}const needed=Math.ceil((y+rowH+.5)/10)*10;if(needed>lengthCm()&&needed<=500)$('sheetLength').value=Math.max(50,needed);updateDimensions();select(items[0]||null);status('Acomodo automático aplicado con separación de 5 mm.')};
$('sheetLength').onchange=()=>{for(const item of items)clamp(item);updateDimensions()};$('sheetDpi').onchange=updateDimensions;$('zoomSheetIn').onclick=()=>{sheetFit=false;zoom=Math.min(3,zoom*1.2);render()};$('zoomSheetOut').onclick=()=>{sheetFit=false;zoom=Math.max(.25,zoom/1.2);render()};$('fitSheet').onclick=fitSheet;const sheetWrap=document.querySelector('.pliego-wrap');sheetWrap.addEventListener('wheel',event=>{event.preventDefault();sheetFit=false;zoom=Math.max(.25,Math.min(3,zoom*(event.deltaY<0?1.12:1/1.12)));render()},{passive:false});new ResizeObserver(()=>{if(sheetFit)fitSheet()}).observe(sheetWrap);
function auditItem(item){const max=700,scale=Math.min(1,max/Math.max(item.image.width,item.image.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(item.image.width*scale));c.height=Math.max(1,Math.round(item.image.height*scale));const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(item.image,0,0,c.width,c.height);const d=x.getImageData(0,0,c.width,c.height).data;let semi=0,thin=0,solid=0;for(let y=1;y<c.height-1;y++)for(let xx=1;xx<c.width-1;xx++){const p=y*c.width+xx,i=p*4,a=d[i+3];if(a>0&&a<255)semi++;if(a>=128){solid++;let n=0;for(const o of [-c.width-1,-c.width,-c.width+1,-1,1,c.width-1,c.width,c.width+1])if(d[(p+o)*4+3]>=128)n++;if(n<=2)thin++}}return {semi,thin,solid}}
async function auditAll(){let semi=0,thin=0,solid=0;for(const item of items){const r=auditItem(item);semi+=r.semi;thin+=r.thin;solid+=r.solid;await new Promise(requestAnimationFrame)}const thinPct=solid?thin/solid*100:0;$('sheetAudit').innerHTML=`<div class="audit-row ${semi?'bad':'good'}"><span class="audit-icon">${semi?'!':'✓'}</span><b>Semitransparencias</b><small>${semi?`${semi.toLocaleString()} detectadas; ${$('sheetSolidAlpha').checked?'se convertirán a alfa sólido':'se conservarán sin cambios'}.`:'Sin problemas detectados.'}</small></div><div class="audit-row ${thinPct>.8?'bad':'good'}"><span class="audit-icon">${thinPct>.8?'!':'✓'}</span><b>Grosor</b><small>${thinPct>.8?`${thinPct.toFixed(2)} % de detalles aislados; revisa líneas muy finas.`:'Sin detalles aislados relevantes.'}</small></div>`;return {semi,thinPct}}
function cmykRoundTrip(r,g,b){let R=r/255,G=g/255,B=b/255,K=1-Math.max(R,G,B),C=K===1?0:(1-R-K)/(1-K),M=K===1?0:(1-G-K)/(1-K),Y=K===1?0:(1-B-K)/(1-K),total=C+M+Y+K;if(total>2.8){const scale=(2.8-K)/(C+M+Y||1);C*=scale;M*=scale;Y*=scale}return [255*(1-C)*(1-K),255*(1-M)*(1-K),255*(1-Y)*(1-K)]}
function processBand(data){const vibrant=$('sheetVibrance').checked,cmyk=$('cmykSafe').checked,solid=$('sheetSolidAlpha').checked;if(!vibrant&&!cmyk&&!solid)return;for(let i=0;i<data.length;i+=4){const a=data[i+3];if(solid){if(a<128){data[i]=data[i+1]=data[i+2]=data[i+3]=0;continue}data[i+3]=255;}if(a===0)continue;if(vibrant){const avg=(data[i]+data[i+1]+data[i+2])/3;data[i]=Math.max(0,Math.min(255,data[i]+(data[i]-avg)*.18));data[i+1]=Math.max(0,Math.min(255,data[i+1]+(data[i+1]-avg)*.18));data[i+2]=Math.max(0,Math.min(255,data[i+2]+(data[i+2]-avg)*.18))}if(cmyk){const out=cmykRoundTrip(data[i],data[i+1],data[i+2]);data[i]=out[0];data[i+1]=out[1];data[i+2]=out[2]}}}
async function exportSheet(size=null,onProgress=null,returnOnly=false){if(!items.length||exporting)return;if(typeof CompressionStream==='undefined'){status('Este navegador no permite exportar pliegos grandes. Usa Chrome, Edge o Safari reciente.',true);return}exporting=true;render();const dialog=$('sheetExportDialog'),progress=$('sheetExportProgress');dialog.showModal();progress.value=0;$('sheetExportText').textContent='Ejecutando Analizador DTF…';try{const audit=await auditAll(),base=dimensions(),dpi=size?.dpi||base.dpi,exportWidth=size?.widthCm||SHEET_WIDTH_CM,w=Math.round(exportWidth/2.54*dpi),h=Math.round(w*lengthCm()/SHEET_WIDTH_CM),mp=w*h/1e6;if(mp>410)throw Error('El pliego supera 410 MP. Reduce el largo o usa 150 ppp.');const compressor=new CompressionStream('deflate'),writer=compressor.writable.getWriter(),compressedPromise=new Response(compressor.readable).arrayBuffer(),rowsPerBand=32,band=document.createElement('canvas');band.width=w;const pxPerCm=w/SHEET_WIDTH_CM;for(let y=0;y<h;y+=rowsPerBand){const rows=Math.min(rowsPerBand,h-y),scanlines=new Uint8Array(rows*(w*4+1)),bandTop=y/pxPerCm,bandBottom=(y+rows)/pxPerCm,visible=items.filter(item=>{const b=rotatedBounds(item);return item.y+b.h/2>=bandTop&&item.y-b.h/2<=bandBottom});if(visible.length){band.height=rows;const bctx=band.getContext('2d',{willReadFrequently:true});bctx.clearRect(0,0,w,rows);drawArtwork(bctx,pxPerCm,y,visible);const image=bctx.getImageData(0,0,w,rows);processBand(image.data);for(let row=0;row<rows;row++)scanlines.set(image.data.subarray(row*w*4,(row+1)*w*4),row*(w*4+1)+1)}await writer.write(scanlines);const percent=Math.round((y+rows)/h*100);progress.value=percent;onProgress?.(percent/100);$('sheetExportLabel').textContent=percent+' %';$('sheetExportText').textContent=`Procesando por bloques · ${percent} %`;if(y%(rowsPerBand*8)===0)await new Promise(requestAnimationFrame)}await writer.close();const compressed=new Uint8Array(await compressedPromise),blob=assemblePng(w,h,dpi,compressed);if(returnOnly)return {blob,width:w,height:h,dpi,widthCm:exportWidth,name:`LZ_pliego_${exportWidth}x${(exportWidth*lengthCm()/SHEET_WIDTH_CM).toFixed(2)}cm.png`};const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`LZ_pliego_58x${lengthCm()}cm_${dpi}ppp_DTF.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);status(`Pliego exportado · ${w} × ${h} px. ${$('sheetSolidAlpha').checked?'Alfa sólido aplicado':'Alfa original conservado'}${audit.thinPct>.8?'; revisa la advertencia de grosor':''}.`)}catch(error){status(error.message||'No se pudo exportar el pliego.',true);if(returnOnly)throw error;}finally{dialog.close();exporting=false;render()}}
for(const id of ['sheetVibrance','cmykSafe','sheetSolidAlpha'])$(id).addEventListener('change',()=>{render();status('Opciones de salida actualizadas. Revisa la vista previa antes de exportar.');});
$('downloadSheet').onclick=()=>exportSheet();updateDimensions();requestAnimationFrame(fitSheet);
registerStudioModule({id:'sheet',getExportInfo:()=>{if(!items.length)throw Error('Agrega un diseño al pliego.');return {widthCm:SHEET_WIDTH_CM,dpi:Number($('sheetDpi').value),aspect:SHEET_WIDTH_CM/lengthCm(),maxPixels:410e6,maxSide:72000};},exportAtSize:(size,onProgress)=>exportSheet(size,onProgress,true),onFit:fitSheet,getDraft:()=>items.length?{images:Object.fromEntries(items.map(item=>[String(item.id),item.image])),data:{items:items.map(({image,url,...item})=>item),selected:selected?.id,nextId}}:null,restoreDraft:async d=>{for(const item of items){item.image.close?.();URL.revokeObjectURL(item.url);}items=[];for(const saved of d.data.items){const blob=d.images[String(saved.id)];items.push({...saved,image:await createImageBitmap(blob),url:URL.createObjectURL(blob)});}nextId=d.data.nextId;selected=items.find(i=>i.id===d.data.selected)||items[0];updateDimensions();select(selected);},afterRestore:()=>{updateDimensions();select(selected);},onZoom:factor=>{sheetFit=false;zoom=Math.max(.25,Math.min(3,zoom*factor));render();},canPan:event=>{const p=pointer(event);return !resizeHit(p,event)&&!hitTest(p.x,p.y)},exportCurrent:async()=>{requireTransferImage(selected?.image,exporting);return canvasArtifact(selected.image,selected.name.replace(/\.[^.]+$/,'')+'_LZ_diseno.png',selected.image.width/selected.widthCm*2.54,selected.widthCm)},importCurrent:async(blob,name,meta)=>{const count=items.length;await addFiles([new File([blob],name,{type:blob.type})]);if(items.length===count)return false;if(meta?.widthCm<=57&&meta.widthCm/selected.aspectRatio<=lengthCm()){selected.widthCm=meta.widthCm;selected.heightCm=meta.widthCm/selected.aspectRatio;clamp(selected);syncControls();renderList();render()}return true}});
