import {registerStudioModule} from './studio-shell.js';
import {decodeImageFile,validateImportSize} from './upscale-import.js';
import {upscaleWorkingSize} from './upscale-runner.js';
import {enhancePremiumCnn} from './premium-cnn.js';
import {createOnnxSuperResolution,prefetchSuperResolution} from './ai-engine.js';
import {outputDimensions} from './image-output.js';
import {workerRequest,runPremiumPipeline} from './premium-pipeline.js';
import {requireTransferImage} from './transfer-export.js';
const $=id=>document.getElementById(id),canvas=$('premiumCanvas'),wrap=document.querySelector('.lab-canvas-wrap');
let source=null,prepared=null,result=null,artifact=null,filename='diseno',busy=false,controller=null,view='original',colorChosen=false,zone=null,mode=null,gesture=null,fit=true,zoom=1;
const engines={webgpu:null,wasm:null};let aiPrefetch=null;
function prefetchCnn(){if(!aiPrefetch)aiPrefetch=prefetchSuperResolution(navigator.gpu?'webgpu':'wasm').catch(()=>false);return aiPrefetch;}
function showGarment(){const value=$('previewGarment').value,custom=value==='custom';$('previewGarmentCustom').hidden=!custom;const color=custom?$('previewGarmentColor').value:value;wrap.classList.toggle('checker',color==='transparent');wrap.style.backgroundColor=color==='transparent'?'':color;wrap.style.backgroundImage=color==='transparent'?'':'none';}
$('previewGarment').onchange=showGarment;$('previewGarmentColor').oninput=showGarment;$('previewGarmentColor').onchange=showGarment;
function status(text,error=false){$('premiumStatus').textContent=text;$('premiumStatus').classList.toggle('error',error);}
function measure(){return outputDimensions(Number($('widthCm').value),Number($('dpi').value),(prepared||source).width/(prepared||source).height);}
function validMeasure(){if(!source)return false;try{const d=measure();$('premiumSize').textContent=`${d.widthCm} × ${(d.widthCm/(source.width/source.height)).toFixed(2)} cm · ${d.width.toLocaleString()} × ${d.height.toLocaleString()} px`;$('premiumSize').classList.remove('error');return true;}catch(error){$('premiumSize').textContent=error.message;$('premiumSize').classList.add('error');return false;}}
function controls(){const valid=validMeasure();$('premiumFile').disabled=busy;$('widthCm').disabled=$('dpi').disabled=busy;$('premiumChoices').disabled=busy||!prepared;$('runPremium').disabled=busy||!prepared||!colorChosen||!valid||($('premiumZone').value==='rect'&&!zone)||!!mode;$('downloadPremium').disabled=busy||!artifact;$('cancelPremium').hidden=!busy;$('premiumOriginal').disabled=busy||!source;$('premiumPrepared').disabled=busy||!prepared;$('premiumResult').disabled=busy||!result;$('retryPremium').hidden=!source||!!prepared||busy;}
function stage(name){let reached=false;for(const li of $('premiumSteps').children){if(li.dataset.stage===name){li.dataset.state='active';reached=true;}else li.dataset.state=reached?'waiting':'done';}}
function complete(){for(const li of $('premiumSteps').children)li.dataset.state='done';$('premiumProgress').value=100;}
function waiting(){for(const li of $('premiumSteps').children)li.dataset.state=['vivid','ai'].includes(li.dataset.stage)&&prepared?'done':'waiting';}
function progress(value){$('premiumProgress').hidden=false;$('premiumProgress').value=Math.round(value*100);}
function layout(){if(canvas.hidden)return;const scale=Math.max(.03,Math.min(5,fit?Math.min((wrap.clientWidth-20)/canvas.width,(wrap.clientHeight-20)/canvas.height):zoom));canvas.style.width=canvas.width*scale+'px';canvas.style.height=canvas.height*scale+'px';$('premiumZoomLabel').textContent=fit?'Ajustar':Math.round(scale*100)+' %';if(fit)zoom=scale;}
function show(){const image=view==='result'?result:view==='prepared'?prepared:source;if(!image)return;const scale=Math.min(1,1400/Math.max(image.width,image.height));canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));const ctx=canvas.getContext('2d');ctx.drawImage(image,0,0,canvas.width,canvas.height);
 const box=gesture?.box||zone;if(view==='prepared'&&$('premiumZone').value==='rect'&&box){ctx.save();ctx.strokeStyle='#bdff67';ctx.lineWidth=2;ctx.setLineDash([6,4]);ctx.strokeRect(box.x*canvas.width,box.y*canvas.height,box.width*canvas.width,box.height*canvas.height);ctx.restore();}
 canvas.hidden=false;$('premiumEmpty').hidden=true;for(const [id,v] of [['premiumOriginal','original'],['premiumPrepared','prepared'],['premiumResult','result']]){$(id).classList.toggle('active',view===v);$(id).setAttribute('aria-pressed',String(view===v));}layout();document.dispatchEvent(new Event('lz-work-changed'));}
function stopSelecting(){mode=null;gesture=null;document.body.classList.remove('picking','premium-selecting');$('pickPremium').setAttribute('aria-pressed','false');$('drawPremiumZone').setAttribute('aria-pressed','false');controls();show();}
function invalidate(){artifact=null;result?.close?.();result=null;if(view==='result')view='prepared';$('premiumReport').textContent='El resultado se comprobará a la medida final de impresión.';waiting();controls();show();}
async function getEngine(backend){await prefetchCnn();if(!engines[backend])engines[backend]=await createOnnxSuperResolution(backend,(value,phase)=>{if(!controller?.signal.aborted)status(phase==='ready'?'CNN de Semitonos listo. Mejorando imagen…':`Preparando CNN de Semitonos · ${Math.round(value)} %`);});return engines[backend];}
async function prepare(){if(!source||busy)return;busy=true;controller=new AbortController();const signal=controller.signal;prefetchCnn();controls();let copy=null,worker=null;
 try{
  stage('vivid');status('1 / 7 · Aplicando colores Vívido…');progress(0);
  const size=upscaleWorkingSize(source.width,source.height);copy=document.createElement('canvas');copy.width=size.width;copy.height=size.height;const ctx=copy.getContext('2d',{willReadFrequently:true});ctx.drawImage(source,0,0,copy.width,copy.height);
  const image=ctx.getImageData(0,0,copy.width,copy.height);worker=new Worker('premium-worker.js',{type:'module'});const bytes=await workerRequest(worker,{type:'vivid',buffer:image.data.buffer,width:copy.width,height:copy.height,widthCm:Number($('widthCm').value)||28},[image.data.buffer],signal);ctx.putImageData(new ImageData(new Uint8ClampedArray(bytes.buffer),copy.width,copy.height),0,0);worker.terminate();worker=null;
  signal.throwIfAborted();stage('ai');status('2 / 7 · Mejorando imagen con CNN ×2 de Semitonos…');let backend='wasm';if(navigator.gpu)try{if(await navigator.gpu.requestAdapter({powerPreference:'high-performance'}))backend='webgpu';}catch{}
  const onProgress=({percent,done,total})=>{progress(percent/100);status(`2 / 7 · CNN de Semitonos · ${Math.round(percent)} % · bloque ${done}/${total}`);};
  let improved;try{const engine=await getEngine(backend);signal.throwIfAborted();improved=await enhancePremiumCnn(copy,engine,{onProgress,signal});}catch(error){if(backend!=='webgpu'||signal.aborted)throw error;try{await engines.webgpu?.dispose?.();}catch{}engines.webgpu=null;status('Reintentando la misma IA en CPU…');const engine=await getEngine('wasm');signal.throwIfAborted();improved=await enhancePremiumCnn(copy,engine,{onProgress,signal});}
  if(signal.aborted){improved.width=improved.height=1;signal.throwIfAborted();}prepared=improved;view='prepared';fit=true;waiting();show();$('premiumProgress').hidden=true;
  $('premiumName').textContent=`${filename} · original ${source.width.toLocaleString()} × ${source.height.toLocaleString()} px · IA ×2 ${prepared.width.toLocaleString()} × ${prepared.height.toLocaleString()} px${copy.width!==source.width||copy.height!==source.height?' (desde copia de trabajo)':''}`;
  status('Imagen mejorada. Elige el color a eliminar y la zona; después pulsa Crear semitono Premium.');
 }catch(error){waiting();status(error.name==='AbortError'?'Preparación cancelada. Puedes reintentar con tu original.':'No se pudo preparar la imagen. '+String(error.message||'').slice(0,180),error.name!=='AbortError');}
 finally{worker?.terminate();if(copy)copy.width=copy.height=1;busy=false;controller=null;controls();}
}
async function upload(file,{savedPrepared=null,savedState=null}={}){if(!file||busy)return false;let image=null;busy=true;controls();status('Cargando imagen…');try{
 image=await decodeImageFile(file);validateImportSize(image.width,image.height);source?.close?.();prepared?.close?.();result?.close?.();if(prepared?.getContext)prepared.width=prepared.height=1;
 source=image;prepared=null;result=null;artifact=null;filename=file.name;view='original';zone=null;colorChosen=false;mode=null;gesture=null;document.body.classList.remove('picking','premium-selecting');$('garmentColor').value='';$('premiumZone').value='all';$('drawPremiumZone').hidden=true;$('premiumName').textContent=file.name;$('premiumColorInfo').textContent='Elige el color de la prenda o selecciónalo en la imagen mejorada.';$('premiumZoneInfo').textContent='Se buscará ese color en toda la imagen.';$('premiumReport').textContent='El resultado se comprueba a la medida final de impresión.';waiting();fit=true;show();
 if(savedPrepared){prepared=await createImageBitmap(savedPrepared);validateImportSize(prepared.width,prepared.height);if(savedState){zone=savedState.zone;colorChosen=Boolean(savedState.colorChosen);$('premiumZone').value=zone?'rect':'all';$('drawPremiumZone').hidden=!zone;}$('premiumColorInfo').textContent=colorChosen?`Color a eliminar: ${$('premiumColor').value.toUpperCase()}`:'Selecciona un color para continuar.';view='prepared';waiting();show();status('Trabajo recuperado. Crea el semitono para verificarlo nuevamente.');}
 }catch(error){if(image!==source)image?.close?.();status(error.message||'No se pudo abrir la imagen.',true);return false;}finally{busy=false;controls();$('premiumFile').value='';}
 if(!savedPrepared)await prepare();return true;
}
function chooseColor(hex){if(busy||!prepared)return;if(mode)stopSelecting();$('premiumColor').value=hex;colorChosen=true;$('premiumColorInfo').textContent=`Color a eliminar: ${hex.toUpperCase()}`;invalidate();status('Color elegido. Revisa la zona y crea el semitono Premium.');}
$('premiumFile').onchange=()=>upload($('premiumFile').files[0]);$('retryPremium').onclick=prepare;$('cancelPremium').onclick=()=>{controller?.abort();status('Cancelando el proceso…');};
$('garmentColor').onchange=()=>{const hex=$('garmentColor').value;if(hex==='custom'){$('premiumColor').focus();$('premiumColor').click();}else if(hex)chooseColor(hex);};
$('premiumColor').oninput=()=>chooseColor($('premiumColor').value);$('premiumColor').onchange=()=>chooseColor($('premiumColor').value);
$('pickPremium').onclick=()=>{if(busy||!prepared)return;if(mode==='color'){stopSelecting();return;}stopSelecting();mode='color';view='prepared';document.body.classList.add('picking');$('pickPremium').setAttribute('aria-pressed','true');status('Toca en la imagen mejorada el color que quieres eliminar.');controls();show();};
$('premiumZone').onchange=()=>{if(busy)return;stopSelecting();zone=null;$('drawPremiumZone').hidden=$('premiumZone').value!=='rect';$('premiumZoneInfo').textContent=$('premiumZone').value==='rect'?'Selecciona una zona rectangular en la imagen.':'Se buscará ese color en toda la imagen.';invalidate();};
$('drawPremiumZone').onclick=()=>{if(busy||!prepared)return;if(mode==='zone'){stopSelecting();return;}stopSelecting();mode='zone';view='prepared';document.body.classList.add('picking','premium-selecting');$('drawPremiumZone').setAttribute('aria-pressed','true');status('Arrastra en la imagen para delimitar la zona donde quitar el color.');controls();show();};
function point(event){const r=canvas.getBoundingClientRect();if(!r.width||!r.height)return null;return {x:Math.max(0,Math.min(1,(event.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(event.clientY-r.top)/r.height))};}
function box(a,b){return {x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),width:Math.abs(a.x-b.x),height:Math.abs(a.y-b.y)};}
canvas.addEventListener('pointerdown',event=>{if(!mode||busy||!prepared||event.button!==0||event.isPrimary===false)return;const a=point(event);if(!a)return;event.preventDefault();gesture={id:event.pointerId,a,box:null};canvas.setPointerCapture(event.pointerId);});
canvas.addEventListener('pointermove',event=>{if(mode!=='zone'||gesture?.id!==event.pointerId)return;const b=point(event);if(!b)return;gesture.box=box(gesture.a,b);show();});
canvas.addEventListener('pointerup',event=>{if(!gesture||gesture.id!==event.pointerId)return;event.preventDefault();const b=point(event),a=gesture.a,selecting=mode;if(canvas.hasPointerCapture(event.pointerId))canvas.releasePointerCapture(event.pointerId);gesture=null;
 if(!b)return;if(selecting==='color'){if(Math.hypot(b.x-a.x,b.y-a.y)>.03)return;const sample=document.createElement('canvas');sample.width=sample.height=1;const ctx=sample.getContext('2d');ctx.drawImage(prepared,Math.min(prepared.width-1,Math.floor(b.x*prepared.width)),Math.min(prepared.height-1,Math.floor(b.y*prepared.height)),1,1,0,0,1,1);const pixel=ctx.getImageData(0,0,1,1).data;if(!pixel[3]){status('Ese píxel es transparente. Elige un color visible.');return;}stopSelecting();$('garmentColor').value='custom';chooseColor('#'+[...pixel.slice(0,3)].map(v=>v.toString(16).padStart(2,'0')).join(''));}
 else if(selecting==='zone'){const selected=box(a,b);if(selected.width*prepared.width<1||selected.height*prepared.height<1){status('Dibuja una zona más grande.');show();return;}zone=selected;stopSelecting();$('premiumZoneInfo').textContent=`Zona seleccionada · ${(zone.width*100).toFixed(1)} % de ancho × ${(zone.height*100).toFixed(1)} % de alto`;invalidate();status('Zona elegida. Puedes crear tu semitono Premium.');}
});
canvas.addEventListener('pointercancel',()=>{gesture=null;show();});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&mode){stopSelecting();status('Selección cancelada.');}});
for(const id of ['widthCm','dpi'])$(id).addEventListener('input',()=>{if(!busy&&prepared)invalidate();else controls();});$('dpi').addEventListener('change',()=>{if(!busy&&prepared)invalidate();});
const labels={halftone:'3 / 7 · Creando semitono · 25 LPI / rango 30…',shrink:'4 / 7 · Auditor: reduciendo 1 píxel…',opacity:'5 / 7 · Analizando y corrigiendo semitransparencias…',thickness:'6 / 7 · Corrigiendo puntos a un mínimo de 0.5 mm…',verify:'7 / 7 · Comprobando el archivo final…'};
function reportText(a){return `Verificado a ${a.widthCm} cm · ${a.dpi} ppp: 0 puntos aislados menores de 0.5 mm y 0 píxeles semitransparentes.${a.report.purged?` Se eliminaron ${a.report.purged.toLocaleString()} puntos residuales que no pudieron reforzarse.`:''}`;}
async function create(size,{exporting=false,onProgress}={}){requireTransferImage(prepared,busy);if(!colorChosen)throw Error('Selecciona el color a eliminar.');if($('premiumZone').value==='rect'&&!zone)throw Error('Selecciona la zona a eliminar.');busy=true;controller=new AbortController();controls();const previous=artifact;
 try{const next=await runPremiumPipeline({source:prepared,color:$('premiumColor').value,zone:$('premiumZone').value==='rect'?zone:null,...size,signal:controller.signal,onStage:name=>{stage(name);status(labels[name]);},onProgress:value=>{progress(value);onProgress?.(value);}});next.name=filename.replace(/\.[^.]+$/,'').replace(/[^a-z0-9áéíóúñ _-]/gi,'').slice(0,80)+'_LZ_semitonos_Premium.png';
  if(!exporting){const bitmap=await createImageBitmap(next.blob);if(controller.signal.aborted){bitmap.close?.();controller.signal.throwIfAborted();}result?.close?.();result=bitmap;artifact=next;view='result';show();}complete();$('premiumReport').textContent=(exporting?'Última descarga: ':'')+reportText(next);status(exporting?'Archivo comprobado para la medida de descarga.':'Semitono Premium verificado. Compara el resultado y descarga tu PNG.');return next;
 }catch(error){if(previous)complete();else waiting();status(error.name==='AbortError'?'Proceso cancelado. Puedes volver a crear el semitono.':error.message||'No se pudo completar el proceso.',error.name!=='AbortError');throw error;}
 finally{busy=false;controller=null;controls();}
}
$('runPremium').onclick=async()=>{try{await create(measure());}catch{}};
for(const [id,value] of [['premiumOriginal','original'],['premiumPrepared','prepared'],['premiumResult','result']])$(id).onclick=()=>{stopSelecting();view=value;show();};
const onFit=()=>{fit=true;wrap.scrollTo(0,0);layout();},onZoom=factor=>{if(!source)return;fit=false;zoom=Math.max(.03,Math.min(5,zoom*factor));layout();};
$('premiumFit').onclick=onFit;$('premiumZoomIn').onclick=()=>onZoom(1.25);$('premiumZoomOut').onclick=()=>onZoom(.8);new ResizeObserver(()=>{if(fit)layout();}).observe(wrap);
function menu(open){$('moduleMenu').hidden=!open;$('menuBackdrop').hidden=!open;$('menuButton').setAttribute('aria-expanded',String(open));}$('menuButton').onclick=()=>menu($('moduleMenu').hidden);$('menuClose').onclick=()=>menu(false);$('menuBackdrop').onclick=()=>menu(false);document.addEventListener('keydown',event=>{if(event.key==='Escape')menu(false);});
window.addEventListener('pagehide',()=>controller?.abort());controls();
registerStudioModule({id:'premium',onFit,onZoom,getComparison:()=>[source,result||prepared],getExportInfo:()=>artifact?{widthCm:artifact.widthCm,dpi:artifact.dpi,aspect:prepared.width/prepared.height}:null,
 exportAtSize:async(size,onProgress)=>{requireTransferImage(artifact,busy);if(size.width===artifact.width&&size.height===artifact.height&&size.widthCm===artifact.widthCm&&size.dpi===artifact.dpi){$('premiumReport').textContent=reportText(artifact);onProgress?.(1);return artifact;}return create(size,{exporting:true,onProgress});},
 cancelExport:()=>controller?.abort(),exportCurrent:async()=>{requireTransferImage(artifact,busy);return artifact;},importCurrent:async(blob,name,meta)=>{if(meta?.widthCm)$('widthCm').value=meta.widthCm;if(meta?.dpi)$('dpi').value=meta.dpi;return upload(new File([blob],name,{type:blob.type}));},
 getDraft:()=>source&&!busy?{images:{source,prepared},data:{filename,colorChosen,zone}}:null,restoreDraft:async d=>{if(busy)throw Error('Espera a que termine el proceso actual.');const ok=await upload(new File([d.images.source],d.data.filename,{type:'image/png'}),{savedPrepared:d.images.prepared,savedState:d.data});if(!ok)throw Error('No se pudo recuperar la imagen.');},afterRestore:()=>{controls();showGarment();show();},restoreFavorite:()=>{colorChosen=true;zone=null;if($('premiumZone').value==='rect')$('premiumZone').value='all';$('drawPremiumZone').hidden=true;showGarment();invalidate();}});
