import {canvasArtifact,processedArtifact,requireTransferImage} from './transfer-export.js';
import {registerStudioModule} from './studio-shell.js';

const $=id=>document.getElementById(id),canvas=$('textCanvas'),ctx=canvas.getContext('2d'),PREVIEW_MAX_SIDE=1600;
const presetNames={urban:'Urban',college:'College',graffiti:'Graffiti',gothic:'Gótico',script:'Script',stencil:'Stencil',retro:'Retro',condensed:'Condensado'};
const effectNames={solid:'sólido',gradient:'degradado',gold:'oro metálico',chrome:'cromo',emerald:'esmeralda',neon:'neón',fire:'fuego',ice:'hielo'};
const presets={
 urban:{font:"'Bebas Neue', Impact, sans-serif",size:390,spacing:6,skew:0,outline:22,outline2:8,depth:18},
 college:{font:"'Graduate', Georgia, serif",size:290,spacing:10,skew:0,outline:24,outline2:9,depth:12},
 graffiti:{font:"'Permanent Marker', cursive",size:340,spacing:2,skew:-7,outline:25,outline2:8,depth:22},
 gothic:{font:"'UnifrakturCook', Georgia, serif",size:390,spacing:3,skew:0,outline:18,outline2:6,depth:14},
 script:{font:"'Permanent Marker', cursive",size:350,spacing:0,skew:-5,outline:15,outline2:5,depth:12},
 stencil:{font:"'Black Ops One', Impact, sans-serif",size:300,spacing:4,skew:0,outline:17,outline2:0,depth:19},
 retro:{font:"'Bungee', Impact, sans-serif",size:280,spacing:5,skew:0,outline:18,outline2:9,depth:15},
 condensed:{font:"'Oswald', 'Arial Narrow', sans-serif",size:410,spacing:1,skew:0,outline:18,outline2:5,depth:20}
};
let activePreset='urban',activeEffect='solid',zoom=1,fitView=true,renderFrame=0,customFontData='';
const value=id=>$(id).value,number=id=>Number(value(id))||0;
const outputDimensions=()=>value('canvasSize').split('x').map(Number);
function textLines(){const raw=value('textValue').trim()||'TU TEXTO',text=$('uppercase').checked?raw.toLocaleUpperCase('es-MX'):raw;return text.split(/\n/).slice(0,4)}
function fontString(){return `900 ${number('fontSize')}px ${value('fontFamily')}`}
function measureSpaced(context,text,spacing){let width=0;for(const char of text)width+=context.measureText(char).width+spacing;return Math.max(0,width-spacing)}
function gradientStops(){const custom=[[0,value('color1')],[1,value('color2')]],sets={gradient:custom,gold:[[0,'#5b3300'],[.18,'#f4d56b'],[.35,'#fff3b0'],[.5,'#9c5d00'],[.7,'#ffd85a'],[1,'#5b3300']],chrome:[[0,'#22282d'],[.18,'#f9ffff'],[.38,'#78828a'],[.5,'#ffffff'],[.62,'#333b42'],[.82,'#e8f3f7'],[1,'#20252a']],emerald:[[0,'#062519'],[.28,'#20d884'],[.5,'#d0ffe1'],[.66,'#08794b'],[1,'#02150d']],neon:[[0,'#8cf7ff'],[.45,'#ffffff'],[.55,'#ff3bd4'],[1,'#6f00ff']],fire:[[0,'#fff78a'],[.35,'#ffb000'],[.7,'#ff3b00'],[1,'#480000']],ice:[[0,'#ffffff'],[.3,'#bff7ff'],[.58,'#36b8ff'],[1,'#103a8a']]};return sets[activeEffect]||custom}
function gradientFill(context,w,h){if(activeEffect==='solid')return value('color1');let gradient;if(value('gradientDirection')==='horizontal')gradient=context.createLinearGradient(0,0,w,0);else if(value('gradientDirection')==='diagonal')gradient=context.createLinearGradient(0,h,w,0);else gradient=context.createLinearGradient(0,0,0,h);for(const [offset,color] of gradientStops())gradient.addColorStop(offset,color);return gradient}
function forEachGlyph(context,text,baseY,callback){const spacing=number('letterSpacing'),total=measureSpaced(context,text,spacing),curve=number('curve');let x=-total/2;for(const char of text){const width=context.measureText(char).width,center=x+width/2,t=total?center/total:0,y=baseY+curve*(1-4*t*t),slope=total?-8*curve*t/total:0;callback(char,center,y,Math.atan(slope));x+=width+spacing}}
function paintLine(context,text,y,style,offsetX=0,offsetY=0){forEachGlyph(context,text,y,(char,x,cy,rotation)=>{context.save();context.translate(x+offsetX,cy+offsetY);context.rotate(rotation);context.transform(1,0,Math.tan(number('skew')*Math.PI/180),1,0,0);context.lineJoin='round';context.lineCap='round';if(style.strokeWidth>0){context.strokeStyle=style.stroke;context.lineWidth=style.strokeWidth;context.strokeText(char,-context.measureText(char).width/2,0)}if(style.fill){context.fillStyle=style.fill;context.fillText(char,-context.measureText(char).width/2,0)}context.restore()})}
function drawArtwork(target,w,h,scale=1){target.canvas.width=Math.max(1,Math.round(w*scale));target.canvas.height=Math.max(1,Math.round(h*scale));target.clearRect(0,0,target.canvas.width,target.canvas.height);target.save();target.scale(scale,scale);target.font=fontString();target.textBaseline='middle';target.textAlign='left';const lines=textLines(),lineGap=number('fontSize')*number('lineHeight')/100,totalHeight=(lines.length-1)*lineGap,startY=-totalHeight/2,outline=number('outlineWidth'),outline2=number('outline2Width'),depth=Math.min(80,number('depth')),shadow=number('shadowBlur'),shadowOffset=number('shadowOffset'),fill=gradientFill(target,w,h);target.translate(w/2,h/2);if(shadow){target.shadowColor=value('shadowColor');target.shadowBlur=shadow;target.shadowOffsetX=shadowOffset;target.shadowOffsetY=shadowOffset}for(const [index,line] of lines.entries()){const y=startY+index*lineGap;if(depth)for(let d=depth;d>0;d-=Math.max(1,Math.ceil(depth/22)))paintLine(target,line,y,{fill:value('depthColor'),stroke:value('depthColor'),strokeWidth:outline+outline2*2},d,d);if(outline2)paintLine(target,line,y,{fill:null,stroke:value('outline2Color'),strokeWidth:outline+outline2*2});if(outline)paintLine(target,line,y,{fill:null,stroke:value('outlineColor'),strokeWidth:outline});paintLine(target,line,y,{fill,stroke:null,strokeWidth:0})}target.restore()}
function render(){if(globalThis.Event)document.dispatchEvent?.(new Event('lz-work-changed'));renderFrame=0;const [w,h]=outputDimensions(),scale=Math.min(1,PREVIEW_MAX_SIDE/Math.max(w,h));drawArtwork(ctx,w,h,scale);$('styleName').textContent=`${presetNames[activePreset]} · ${effectNames[activeEffect]}`;$('textOutputSummary').textContent=`PNG/SVG · ${w} × ${h} px${$('trimOutput').checked?' · recorte automático':''}`;outputs();layout()}
function schedule(){if(!renderFrame)renderFrame=requestAnimationFrame(render)}
function outputs(){$('fontSizeOut').value=value('fontSize')+' px';$('letterSpacingOut').value=value('letterSpacing')+' px';$('lineHeightOut').value=value('lineHeight')+' %';$('skewOut').value=value('skew')+'°';$('shadowBlurOut').value=value('shadowBlur')+' px';const curve=number('curve');$('curveOut').value=curve===0?'Recto':curve>0?'Arco superior '+curve:'Arco inferior '+Math.abs(curve)}
function layout(){const box=document.querySelector('.text-canvas-wrap'),scale=fitView?Math.min((box.clientWidth-20)/canvas.width,(box.clientHeight-20)/canvas.height):zoom,safe=Math.max(.035,Math.min(2,scale));$('textStage').style.width=canvas.width*safe+'px';$('textStage').style.height=canvas.height*safe+'px';$('textZoomLabel').textContent=fitView?'Ajustar':Math.round(safe*100)+' %';if(fitView)zoom=safe}
function applyPreset(name){const p=presets[name];activePreset=name;$('fontFamily').value=p.font;$('fontSize').value=p.size;$('letterSpacing').value=p.spacing;$('skew').value=p.skew;$('outlineWidth').value=p.outline;$('outline2Width').value=p.outline2;$('depth').value=p.depth;for(const button of document.querySelectorAll('[data-preset]'))button.classList.toggle('active',button.dataset.preset===name);schedule()}
function applyEffect(name){activeEffect=name;const maps={solid:['#f7f7f7','#b8ff3d'],gradient:['#ff2aa1','#5b30ff'],gold:['#d99a13','#fff0a0'],chrome:['#f8ffff','#303840'],emerald:['#20d884','#d0ffe1'],neon:['#8cf7ff','#ff3bd4'],fire:['#fff78a','#ff3b00'],ice:['#ffffff','#36b8ff']};[$('color1').value,$('color2').value]=maps[name];if(name==='neon'){$('shadowBlur').value=42;$('shadowColor').value='#ff3bd4'}for(const button of document.querySelectorAll('[data-effect]'))button.classList.toggle('active',button.dataset.effect===name);schedule()}
function exportCanvas(){const [w,h]=outputDimensions(),out=document.createElement('canvas');drawArtwork(out.getContext('2d'),w,h,1);return out}
function trimmedCanvas(source){if(!$('trimOutput').checked)return source;const context=source.getContext('2d',{willReadFrequently:true}),data=context.getImageData(0,0,source.width,source.height).data;let left=source.width,top=source.height,right=-1,bottom=-1;for(let y=0;y<source.height;y++)for(let x=0;x<source.width;x++)if(data[(y*source.width+x)*4+3]>2){left=Math.min(left,x);right=Math.max(right,x);top=Math.min(top,y);bottom=Math.max(bottom,y)}if(right<left)return source;const pad=40,sx=Math.max(0,left-pad),sy=Math.max(0,top-pad),ex=Math.min(source.width,right+pad+1),ey=Math.min(source.height,bottom+pad+1),out=document.createElement('canvas');out.width=ex-sx;out.height=ey-sy;out.getContext('2d').drawImage(source,sx,sy,out.width,out.height,0,0,out.width,out.height);return out}
function blobFromCanvas(target){return new Promise((resolve,reject)=>target.toBlob(blob=>blob?resolve(blob):reject(Error('No se pudo crear el PNG.')),'image/png'))}
async function currentArtifact(){const out=trimmedCanvas(exportCanvas()),blob=await blobFromCanvas(out);return {blob,width:out.width,height:out.height,dpi:300,widthCm:out.width/300*2.54,name:(textLines().join('-')||'texto').replace(/[^a-z0-9áéíóúñ_-]/gi,'-').slice(0,60)+'_LZ.png'}}
async function download(){try{const artifact=await currentArtifact(),url=URL.createObjectURL(artifact.blob),a=document.createElement('a');a.href=url;a.download=artifact.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);const image=await createImageBitmap(artifact.blob);status(`PNG descargado · ${image.width} × ${image.height} px.`);image.close()}catch(error){status(error.message,true)}}
function escapeXml(text){return String(text).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[char]))}
function svgGradient(){if(activeEffect==='solid')return {defs:'',fill:value('color1')};const horizontal=value('gradientDirection')==='horizontal',diagonal=value('gradientDirection')==='diagonal',attrs=horizontal?'x1="0" y1="0" x2="1" y2="0"':diagonal?'x1="0" y1="1" x2="1" y2="0"':'x1="0" y1="0" x2="0" y2="1"',stops=gradientStops().map(([offset,color])=>`<stop offset="${offset*100}%" stop-color="${color}"/>`).join('');return {defs:`<linearGradient id="lzFill" ${attrs}>${stops}</linearGradient>`,fill:'url(#lzFill)'}}
function svgDocument(){const [w,h]=outputDimensions(),lines=textLines(),lineGap=number('fontSize')*number('lineHeight')/100,totalHeight=(lines.length-1)*lineGap,startY=h/2-totalHeight/2,curve=number('curve'),gradient=svgGradient(),outline=number('outlineWidth'),outline2=number('outline2Width'),depth=Math.min(80,number('depth')),family=value('fontFamily'),shadow=number('shadowBlur'),custom=customFontData?`@font-face{font-family:'LZ Custom';src:url('${customFontData}');}`:'',paths=[],definitions=[],art=[];for(const [index,line] of lines.entries()){const y=startY+index*lineGap,id=`lzText${index}`;if(curve){const pathId=`lzCurve${index}`,x1=w*.08,x2=w*.92;paths.push(`<path id="${pathId}" d="M${x1} ${y} Q${w/2} ${y+curve*2} ${x2} ${y}" fill="none"/>`);definitions.push(`<text id="${id}" text-anchor="middle"><textPath href="#${pathId}" startOffset="50%">${escapeXml(line)}</textPath></text>`)}else definitions.push(`<text id="${id}" x="${w/2}" y="${y}" text-anchor="middle" dominant-baseline="middle">${escapeXml(line)}</text>`);if(depth)for(let d=depth;d>0;d-=Math.max(2,Math.ceil(depth/12)))art.push(`<use href="#${id}" transform="translate(${d} ${d})" fill="${value('depthColor')}" stroke="${value('depthColor')}" stroke-width="${outline+outline2*2}"/>`);if(outline2)art.push(`<use href="#${id}" fill="none" stroke="${value('outline2Color')}" stroke-width="${outline+outline2*2}"/>`);if(outline)art.push(`<use href="#${id}" fill="none" stroke="${value('outlineColor')}" stroke-width="${outline}"/>`);art.push(`<use href="#${id}" fill="${gradient.fill}"/>`)}const filter=shadow?`<filter id="lzShadow" x="-30%" y="-30%" width="160%" height="160%"><feDropShadow dx="${number('shadowOffset')}" dy="${number('shadowOffset')}" stdDeviation="${shadow/3}" flood-color="${value('shadowColor')}"/></filter>`:'';return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><title>${escapeXml(textLines().join(' '))} · LZ_STUDIO_TOOLS</title><style>${custom}text{font-family:${escapeXml(family)};font-size:${number('fontSize')}px;font-weight:900;letter-spacing:${number('letterSpacing')}px;font-style:${number('skew')?'italic':'normal'};stroke-linejoin:round;stroke-linecap:round}</style><defs>${gradient.defs}${filter}${paths.join('')}${definitions.join('')}</defs><g${shadow?' filter="url(#lzShadow)"':''}>${art.join('')}</g></svg>`}
function downloadSvg(){const svg=svgDocument(),blob=new Blob([svg],{type:'image/svg+xml'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(textLines().join('-')||'texto').replace(/[^a-z0-9áéíóúñ_-]/gi,'-').slice(0,60)+'_LZ_editable.svg';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);status('SVG editable descargado. Si cargaste una fuente propia, quedó integrada en el archivo.')}
async function loadCustomFont(file){if(!file)return;try{const data=await file.arrayBuffer(),face=new FontFace('LZ Custom',data);await face.load();document.fonts.add(face);customFontData=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});let option=[...$('fontFamily').options].find(item=>item.value==="'LZ Custom'");if(!option){option=document.createElement('option');option.value="'LZ Custom'";option.textContent=`Mi fuente · ${file.name}`;$('fontFamily').append(option)}$('fontFamily').value="'LZ Custom'";$('fontStatus').textContent=`Fuente cargada: ${file.name}. Se integrará al SVG.`;activePreset='urban';schedule()}catch{$('fontStatus').textContent='No se pudo abrir esa fuente. Prueba con TTF, OTF, WOFF o WOFF2.'}finally{$('customFont').value=''}}
function status(message,error=false){$('textStatus').textContent=message;$('textStatus').classList.toggle('error',error)}
for(const input of document.querySelectorAll('.text-tools input:not(#customFont),.text-tools select,.text-tools textarea'))input.addEventListener('input',schedule);
for(const button of document.querySelectorAll('[data-preset]'))button.onclick=()=>applyPreset(button.dataset.preset);for(const button of document.querySelectorAll('[data-effect]'))button.onclick=()=>applyEffect(button.dataset.effect);
$('customFont').onchange=()=>loadCustomFont($('customFont').files[0]);$('downloadText').onclick=download;$('downloadTextSvg').onclick=downloadSvg;$('resetText').onclick=()=>{activeEffect='solid';applyPreset('urban');applyEffect('solid');$('textValue').value='LZ STREET';$('curve').value=0;$('shadowBlur').value=0;$('uppercase').checked=true;schedule();status('Estilo restaurado.')};
$('previewBackground').onchange=()=>{const color=value('previewBackground'),stage=$('textStage');stage.classList.toggle('checker',color==='transparent');stage.style.background=color==='transparent'?'':color};
$('textZoomIn').onclick=()=>{fitView=false;zoom=Math.min(2,zoom*1.25);layout()};$('textZoomOut').onclick=()=>{fitView=false;zoom=Math.max(.035,zoom/1.25);layout()};$('textFit').onclick=()=>{fitView=true;layout()};document.querySelector('.text-canvas-wrap').addEventListener('wheel',event=>{event.preventDefault();fitView=false;zoom=Math.max(.035,Math.min(2,zoom*(event.deltaY<0?1.13:1/1.13)));layout()},{passive:false});new ResizeObserver(()=>{if(fitView)layout()}).observe(document.querySelector('.text-canvas-wrap'));
function toggleMenu(open){$('moduleMenu').hidden=!open;$('menuBackdrop').hidden=!open;$('menuButton').setAttribute('aria-expanded',String(open));if(open)$('menuClose').focus()}$('menuButton').onclick=()=>toggleMenu($('moduleMenu').hidden);$('menuClose').onclick=()=>toggleMenu(false);$('menuBackdrop').onclick=()=>toggleMenu(false);document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!$('moduleMenu').hidden)toggleMenu(false)});
document.fonts?.ready?.then(schedule);render();
registerStudioModule({id:'text',onFit:()=>{fitView=true;layout();},favoriteState:()=>({activePreset,activeEffect}),restoreFavorite:data=>{if(data){activePreset=data.activePreset;activeEffect=data.activeEffect;}schedule();},getDraft:()=>({images:{},data:{activePreset,activeEffect,customFontData}}),restoreDraft:async d=>{activePreset=d.data.activePreset;activeEffect=d.data.activeEffect;customFontData=d.data.customFontData||'';if(customFontData){const face=new FontFace('LZ Custom','url('+customFontData+')');await face.load();document.fonts.add(face);if(![...$('fontFamily').options].some(o=>o.value==="'LZ Custom'"))$('fontFamily').append(new Option('Mi fuente',"'LZ Custom'"));}},afterRestore:()=>schedule(),onZoom:factor=>{fitView=false;zoom=Math.max(.035,Math.min(2,zoom*factor));layout();},exportCurrent:currentArtifact});
