import {canvasArtifact,processedArtifact,requireTransferImage} from './transfer-export.js';
import {registerStudioModule} from './studio-shell.js';
const $=id=>document.getElementById(id);let bitmap=null,svgText='',svgUrl='',fileName='vector-lz',sourceCanvas=null,vectorZoom=1,vectorFit=true,vectorMode=false;
function status(message,error=false){$('vectorStatus').textContent=message;$('vectorStatus').classList.toggle('error',error)}
function menu(open){$('moduleMenu').hidden=!open;$('menuBackdrop').hidden=!open;$('menuButton').setAttribute('aria-expanded',String(open))}$('menuButton').onclick=()=>menu($('moduleMenu').hidden);$('menuClose').onclick=()=>menu(false);$('menuBackdrop').onclick=()=>menu(false);document.addEventListener('keydown',e=>{if(e.key==='Escape')menu(false)});
$('vectorColors').oninput=()=>{$('vectorColorsOut').value=$('vectorColors').value};
function canvasFor(image,maxSide){const scale=Math.min(1,maxSide/Math.max(image.width,image.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(image.width*scale));c.height=Math.max(1,Math.round(image.height*scale));c.getContext('2d',{willReadFrequently:true}).drawImage(image,0,0,c.width,c.height);return c}
function vectorTarget(){return vectorMode&&svgText?$('vectorPreview'):sourceCanvas?$('rasterPreview'):null}
function layoutVector(){const target=vectorTarget();if(!target)return;const wrap=document.querySelector('.lab-canvas-wrap'),width=target.tagName==='IMG'?(target.naturalWidth||sourceCanvas?.width||1):target.width,height=target.tagName==='IMG'?(target.naturalHeight||sourceCanvas?.height||1):target.height,fit=Math.min((wrap.clientWidth-20)/width,(wrap.clientHeight-20)/height),scale=Math.max(.04,Math.min(5,vectorFit?fit:vectorZoom));target.style.width=width*scale+'px';target.style.height=height*scale+'px';$('vectorZoomLabel').textContent=vectorFit?'Ajustar':Math.round(scale*100)+' %';if(vectorFit)vectorZoom=scale}
async function upload(file){if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>40*1024*1024){status('Usa PNG, JPG o WebP de hasta 40 MB.',true);return}try{bitmap?.close?.();bitmap=await createImageBitmap(file,{imageOrientation:'from-image'});if(svgUrl)URL.revokeObjectURL(svgUrl);svgText='';svgUrl='';$('vectorPreview').hidden=true;$('downloadVector').disabled=true;fileName=file.name.replace(/\.[^.]+$/,'');sourceCanvas=canvasFor(bitmap,1200);const preview=$('rasterPreview');preview.width=sourceCanvas.width;preview.height=sourceCanvas.height;preview.getContext('2d').drawImage(sourceCanvas,0,0);preview.style.width=Math.min(sourceCanvas.width,900)+'px';preview.style.height='auto';$('vectorName').textContent=file.name;$('vectorSize').textContent=`${bitmap.width} × ${bitmap.height} px`;$('runVector').disabled=false;$('vectorSummary').textContent='Original cargado · configura la simplificación';$('vectorEmpty').hidden=true;show(false);status('Imagen lista. Ajusta los colores y genera el SVG.');return true;}catch{status('No se pudo abrir esa imagen.',true)}finally{$('vectorFile').value=''}}
$('vectorFile').onchange=()=>upload($('vectorFile').files[0]);
function distance(a,b){const dr=a[0]-b[0],dg=a[1]-b[1],db=a[2]-b[2];return dr*dr+dg*dg+db*db}
function paletteKmeans(data,k){const samples=[];for(let i=0;i<data.length;i+=Math.max(4,Math.floor(data.length/24000/4)*4)){if(data[i+3]>24)samples.push([data[i],data[i+1],data[i+2]])}if(!samples.length)return [[0,0,0]];const centers=[];for(let i=0;i<k;i++)centers.push([...samples[Math.floor(i*(samples.length-1)/Math.max(1,k-1))]]);for(let pass=0;pass<8;pass++){const sums=centers.map(()=>[0,0,0,0]);for(const sample of samples){let best=0,bestD=Infinity;for(let c=0;c<centers.length;c++){const d=distance(sample,centers[c]);if(d<bestD){bestD=d;best=c}}const s=sums[best];s[0]+=sample[0];s[1]+=sample[1];s[2]+=sample[2];s[3]++}for(let c=0;c<centers.length;c++)if(sums[c][3])centers[c]=sums[c].slice(0,3).map(v=>Math.round(v/sums[c][3]))}return centers}
function nearest(rgb,palette){let best=0,bestD=Infinity;for(let i=0;i<palette.length;i++){const d=distance(rgb,palette[i]);if(d<bestD){bestD=d;best=i}}return best}
function escapeXml(value){return value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[char]))}
function quantize(data,w,h,palette,transparent){const labels=new Int16Array(w*h);for(let p=0;p<labels.length;p++){const i=p*4;labels[p]=transparent&&data[i+3]<48?-1:nearest([data[i],data[i+1],data[i+2]],palette)}return labels}
function pixelPaths(labels,w,h,color){const commands=[];for(let y=0;y<h;y++){let x=0;while(x<w){if(labels[y*w+x]!==color){x++;continue}const start=x;while(x<w&&labels[y*w+x]===color)x++;commands.push(`M${start} ${y}h${x-start}v1h-${x-start}z`)}}return commands.join('')}
function contourLoops(labels,w,h,color){const stride=w+1,edges=new Map(),add=(a,b)=>{const list=edges.get(a);if(list)list.push(b);else edges.set(a,[b])};for(let y=0;y<h;y++)for(let x=0;x<w;x++){const p=y*w+x;if(labels[p]!==color)continue;if(y===0||labels[p-w]!==color)add(y*stride+x,y*stride+x+1);if(x===w-1||labels[p+1]!==color)add(y*stride+x+1,(y+1)*stride+x+1);if(y===h-1||labels[p+w]!==color)add((y+1)*stride+x+1,(y+1)*stride+x);if(x===0||labels[p-1]!==color)add((y+1)*stride+x,y*stride+x)}const loops=[];while(edges.size){const start=edges.keys().next().value,path=[],seen=new Set();let current=start;while(!seen.has(current)){seen.add(current);path.push([current%stride,Math.floor(current/stride)]);const from=current,list=edges.get(from);if(!list?.length)break;current=list.pop();if(!list.length)edges.delete(from);if(current===start)break}if(path.length>2)loops.push(path)}return loops}
function cleanLoop(points){if(points.length<4)return points;const straight=[];for(let i=0;i<points.length;i++){const a=points[(i-1+points.length)%points.length],b=points[i],c=points[(i+1)%points.length];if((b[0]-a[0])*(c[1]-b[1])!==(b[1]-a[1])*(c[0]-b[0]))straight.push(b)}if(straight.length<4)return straight;const sampled=[];for(let i=0;i<straight.length;i++){const p=straight[i],last=sampled.at(-1);if(!last||Math.hypot(p[0]-last[0],p[1]-last[1])>=1.5)sampled.push(p)}return sampled.length>2?sampled:straight}
function smoothPath(points){const p=cleanLoop(points);if(p.length<3)return'';const midpoint=(a,b)=>[(a[0]+b[0])/2,(a[1]+b[1])/2],start=midpoint(p.at(-1),p[0]);let d=`M${start[0].toFixed(1)} ${start[1].toFixed(1)}`;for(let i=0;i<p.length;i++){const end=midpoint(p[i],p[(i+1)%p.length]);d+=`Q${p[i][0]} ${p[i][1]} ${end[0].toFixed(1)} ${end[1].toFixed(1)}`}return d+'Z'}
async function vectorize(){if(!bitmap)return;$('vectorBusy').hidden=false;$('runVector').disabled=true;$('vectorProgress').hidden=false;$('vectorProgress').value=8;await new Promise(requestAnimationFrame);try{const c=canvasFor(bitmap,Number($('vectorDetail').value)),ctx=c.getContext('2d',{willReadFrequently:true}),image=ctx.getImageData(0,0,c.width,c.height),data=image.data,k=Number($('vectorColors').value),palette=paletteKmeans(data,k),transparent=$('vectorTransparent').checked,labels=quantize(data,c.width,c.height,palette,transparent),smooth=$('vectorTrace').value==='smooth';$('vectorProgress').value=42;await new Promise(requestAnimationFrame);const paths=palette.map((color,i)=>{const d=smooth?contourLoops(labels,c.width,c.height,i).map(smoothPath).join(''):pixelPaths(labels,c.width,c.height,i);return d?`<path fill="rgb(${color.join(',')})" fill-rule="evenodd" d="${d}"/>`:''}).join(''),background=transparent?'':`<rect width="100%" height="100%" fill="white"/>`;$('vectorProgress').value=82;svgText=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${c.width} ${c.height}" width="${c.width}" height="${c.height}">${background}<title>${escapeXml(fileName)} · LZ_STUDIO_TOOLS</title>${paths}</svg>`;if(svgUrl)URL.revokeObjectURL(svgUrl);svgUrl=URL.createObjectURL(new Blob([svgText],{type:'image/svg+xml'}));$('vectorPreview').src=svgUrl;$('vectorPreview').hidden=false;$('downloadVector').disabled=false;$('vectorSummary').textContent=`${c.width} × ${c.height} unidades · ${palette.length} colores · ${smooth?'contorno suave':'compatibilidad'}`;$('vectorProgress').value=100;show(true);status(smooth?'Vector suave listo, con contornos redondeados y menos escalonado.':'Vector de compatibilidad listo con el método original.')}catch(error){status(error.message||'No se pudo vectorizar la imagen.',true)}finally{$('vectorBusy').hidden=true;$('runVector').disabled=false;$('vectorProgress').hidden=true}}
function show(vector){vectorMode=vector;$('showVector').classList.toggle('active',vector);$('showRaster').classList.toggle('active',!vector);$('vectorPreview').hidden=!vector||!svgText;$('rasterPreview').hidden=vector||!sourceCanvas;$('vectorEmpty').hidden=Boolean(bitmap);requestAnimationFrame(layoutVector)}
$('runVector').onclick=vectorize;$('showVector').onclick=()=>show(true);$('showRaster').onclick=()=>show(false);$('downloadVector').onclick=()=>{if(!svgText)return;const a=document.createElement('a');a.href=svgUrl;a.download=fileName.replace(/[^a-z0-9áéíóúñ_-]/gi,'_')+'_LZ.svg';a.click();status('SVG descargado. Ábrelo en Illustrator o CorelDRAW.')};
$('vectorPreview').onload=layoutVector;$('vectorZoomIn').onclick=()=>{vectorFit=false;vectorZoom=Math.min(5,vectorZoom*1.25);layoutVector()};$('vectorZoomOut').onclick=()=>{vectorFit=false;vectorZoom=Math.max(.04,vectorZoom/1.25);layoutVector()};$('vectorFit').onclick=()=>{vectorFit=true;layoutVector()};const vectorWrap=document.querySelector('.lab-canvas-wrap');vectorWrap.addEventListener('wheel',event=>{if(!vectorTarget())return;event.preventDefault();vectorFit=false;vectorZoom=Math.max(.04,Math.min(5,vectorZoom*(event.deltaY<0?1.14:1/1.14)));layoutVector()},{passive:false});new ResizeObserver(()=>{if(vectorFit)layoutVector()}).observe(vectorWrap);
registerStudioModule({id:'vectorize',onFit:()=>{vectorFit=true;layoutVector();},getComparison:()=>svgText?[sourceCanvas,$('vectorPreview')]:null,getDraft:()=>bitmap?{images:{source:bitmap},data:{fileName,svgText}}:null,restoreDraft:async d=>{await upload(new File([d.images.source],d.data.fileName,{type:'image/png'}));if(d.data.svgText){svgText=d.data.svgText;svgUrl=URL.createObjectURL(new Blob([svgText],{type:'image/svg+xml'}));$('vectorPreview').src=svgUrl;await $('vectorPreview').decode();$('downloadVector').disabled=false;show(true);}},onZoom:factor=>{if(!vectorTarget())return;vectorFit=false;vectorZoom=Math.max(.04,Math.min(5,vectorZoom*factor));layoutVector();},exportCurrent:async()=>{requireTransferImage(bitmap,!$('vectorBusy').hidden);if(!svgText)return canvasArtifact(bitmap,fileName+'_original.png');const img=new Image();img.src=svgUrl;await img.decode();return canvasArtifact(img,fileName+'_vectorizado.png')},importCurrent:async(blob,name)=>upload(new File([blob],name,{type:blob.type}))});
